// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface AddressOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string name = 1;
  /**
   * <code>optional string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // optional string addressLine1 = 2;
  /**
   * <code>optional string addressLine1 = 2;</code>
   */
  boolean hasAddressLine1();
  /**
   * <code>optional string addressLine1 = 2;</code>
   */
  java.lang.String getAddressLine1();
  /**
   * <code>optional string addressLine1 = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressLine1Bytes();

  // optional string addressLine2 = 3;
  /**
   * <code>optional string addressLine2 = 3;</code>
   */
  boolean hasAddressLine2();
  /**
   * <code>optional string addressLine2 = 3;</code>
   */
  java.lang.String getAddressLine2();
  /**
   * <code>optional string addressLine2 = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressLine2Bytes();

  // optional string city = 4;
  /**
   * <code>optional string city = 4;</code>
   */
  boolean hasCity();
  /**
   * <code>optional string city = 4;</code>
   */
  java.lang.String getCity();
  /**
   * <code>optional string city = 4;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  // optional string state = 5;
  /**
   * <code>optional string state = 5;</code>
   */
  boolean hasState();
  /**
   * <code>optional string state = 5;</code>
   */
  java.lang.String getState();
  /**
   * <code>optional string state = 5;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();

  // optional string postalCode = 6;
  /**
   * <code>optional string postalCode = 6;</code>
   */
  boolean hasPostalCode();
  /**
   * <code>optional string postalCode = 6;</code>
   */
  java.lang.String getPostalCode();
  /**
   * <code>optional string postalCode = 6;</code>
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();

  // optional string postalCountry = 7;
  /**
   * <code>optional string postalCountry = 7;</code>
   */
  boolean hasPostalCountry();
  /**
   * <code>optional string postalCountry = 7;</code>
   */
  java.lang.String getPostalCountry();
  /**
   * <code>optional string postalCountry = 7;</code>
   */
  com.google.protobuf.ByteString
      getPostalCountryBytes();

  // optional string dependentLocality = 8;
  /**
   * <code>optional string dependentLocality = 8;</code>
   */
  boolean hasDependentLocality();
  /**
   * <code>optional string dependentLocality = 8;</code>
   */
  java.lang.String getDependentLocality();
  /**
   * <code>optional string dependentLocality = 8;</code>
   */
  com.google.protobuf.ByteString
      getDependentLocalityBytes();

  // optional string sortingCode = 9;
  /**
   * <code>optional string sortingCode = 9;</code>
   */
  boolean hasSortingCode();
  /**
   * <code>optional string sortingCode = 9;</code>
   */
  java.lang.String getSortingCode();
  /**
   * <code>optional string sortingCode = 9;</code>
   */
  com.google.protobuf.ByteString
      getSortingCodeBytes();

  // optional string languageCode = 10;
  /**
   * <code>optional string languageCode = 10;</code>
   */
  boolean hasLanguageCode();
  /**
   * <code>optional string languageCode = 10;</code>
   */
  java.lang.String getLanguageCode();
  /**
   * <code>optional string languageCode = 10;</code>
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes();

  // optional string phoneNumber = 11;
  /**
   * <code>optional string phoneNumber = 11;</code>
   */
  boolean hasPhoneNumber();
  /**
   * <code>optional string phoneNumber = 11;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>optional string phoneNumber = 11;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  // optional bool isReduced = 12;
  /**
   * <code>optional bool isReduced = 12;</code>
   */
  boolean hasIsReduced();
  /**
   * <code>optional bool isReduced = 12;</code>
   */
  boolean getIsReduced();

  // optional string firstName = 13;
  /**
   * <code>optional string firstName = 13;</code>
   */
  boolean hasFirstName();
  /**
   * <code>optional string firstName = 13;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string firstName = 13;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  // optional string lastName = 14;
  /**
   * <code>optional string lastName = 14;</code>
   */
  boolean hasLastName();
  /**
   * <code>optional string lastName = 14;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>optional string lastName = 14;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  // optional string email = 15;
  /**
   * <code>optional string email = 15;</code>
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 15;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 15;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
