// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

/**
 * Protobuf type {@code AlbumDetails}
 */
public  final class AlbumDetails extends
    com.google.protobuf.GeneratedMessage
    implements AlbumDetailsOrBuilder {
  // Use AlbumDetails.newBuilder() to construct.
  private AlbumDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private AlbumDetails(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final AlbumDetails defaultInstance;
  public static AlbumDetails getDefaultInstance() {
    return defaultInstance;
  }

  public AlbumDetails getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private AlbumDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            name_ = input.readBytes();
            break;
          }
          case 18: {
            com.github.yeriomin.playstoreapi.MusicDetails.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = details_.toBuilder();
            }
            details_ = input.readMessage(com.github.yeriomin.playstoreapi.MusicDetails.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(details_);
              details_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            com.github.yeriomin.playstoreapi.ArtistDetails.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = displayArtist_.toBuilder();
            }
            displayArtist_ = input.readMessage(com.github.yeriomin.playstoreapi.ArtistDetails.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(displayArtist_);
              displayArtist_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_AlbumDetails_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_AlbumDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.yeriomin.playstoreapi.AlbumDetails.class, com.github.yeriomin.playstoreapi.AlbumDetails.Builder.class);
  }

  public static com.google.protobuf.Parser<AlbumDetails> PARSER =
      new com.google.protobuf.AbstractParser<AlbumDetails>() {
    public AlbumDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AlbumDetails(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<AlbumDetails> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional string name = 1;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.Object name_;
  /**
   * <code>optional string name = 1;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional .MusicDetails details = 2;
  public static final int DETAILS_FIELD_NUMBER = 2;
  private com.github.yeriomin.playstoreapi.MusicDetails details_;
  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  public boolean hasDetails() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  public com.github.yeriomin.playstoreapi.MusicDetails getDetails() {
    return details_;
  }
  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  public com.github.yeriomin.playstoreapi.MusicDetailsOrBuilder getDetailsOrBuilder() {
    return details_;
  }

  // optional .ArtistDetails displayArtist = 3;
  public static final int DISPLAYARTIST_FIELD_NUMBER = 3;
  private com.github.yeriomin.playstoreapi.ArtistDetails displayArtist_;
  /**
   * <code>optional .ArtistDetails displayArtist = 3;</code>
   */
  public boolean hasDisplayArtist() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .ArtistDetails displayArtist = 3;</code>
   */
  public com.github.yeriomin.playstoreapi.ArtistDetails getDisplayArtist() {
    return displayArtist_;
  }
  /**
   * <code>optional .ArtistDetails displayArtist = 3;</code>
   */
  public com.github.yeriomin.playstoreapi.ArtistDetailsOrBuilder getDisplayArtistOrBuilder() {
    return displayArtist_;
  }

  private void initFields() {
    name_ = "";
    details_ = com.github.yeriomin.playstoreapi.MusicDetails.getDefaultInstance();
    displayArtist_ = com.github.yeriomin.playstoreapi.ArtistDetails.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, details_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, displayArtist_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, details_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, displayArtist_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.github.yeriomin.playstoreapi.AlbumDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.yeriomin.playstoreapi.AlbumDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.AlbumDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.yeriomin.playstoreapi.AlbumDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.AlbumDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.AlbumDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.AlbumDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.AlbumDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.AlbumDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.AlbumDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.github.yeriomin.playstoreapi.AlbumDetails prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AlbumDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.github.yeriomin.playstoreapi.AlbumDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_AlbumDetails_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_AlbumDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.yeriomin.playstoreapi.AlbumDetails.class, com.github.yeriomin.playstoreapi.AlbumDetails.Builder.class);
    }

    // Construct using com.github.yeriomin.playstoreapi.AlbumDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getDetailsFieldBuilder();
        getDisplayArtistFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (detailsBuilder_ == null) {
        details_ = com.github.yeriomin.playstoreapi.MusicDetails.getDefaultInstance();
      } else {
        detailsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (displayArtistBuilder_ == null) {
        displayArtist_ = com.github.yeriomin.playstoreapi.ArtistDetails.getDefaultInstance();
      } else {
        displayArtistBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_AlbumDetails_descriptor;
    }

    public com.github.yeriomin.playstoreapi.AlbumDetails getDefaultInstanceForType() {
      return com.github.yeriomin.playstoreapi.AlbumDetails.getDefaultInstance();
    }

    public com.github.yeriomin.playstoreapi.AlbumDetails build() {
      com.github.yeriomin.playstoreapi.AlbumDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.yeriomin.playstoreapi.AlbumDetails buildPartial() {
      com.github.yeriomin.playstoreapi.AlbumDetails result = new com.github.yeriomin.playstoreapi.AlbumDetails(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (detailsBuilder_ == null) {
        result.details_ = details_;
      } else {
        result.details_ = detailsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (displayArtistBuilder_ == null) {
        result.displayArtist_ = displayArtist_;
      } else {
        result.displayArtist_ = displayArtistBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.yeriomin.playstoreapi.AlbumDetails) {
        return mergeFrom((com.github.yeriomin.playstoreapi.AlbumDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.yeriomin.playstoreapi.AlbumDetails other) {
      if (other == com.github.yeriomin.playstoreapi.AlbumDetails.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasDetails()) {
        mergeDetails(other.getDetails());
      }
      if (other.hasDisplayArtist()) {
        mergeDisplayArtist(other.getDisplayArtist());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.yeriomin.playstoreapi.AlbumDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.yeriomin.playstoreapi.AlbumDetails) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string name = 1;
    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    // optional .MusicDetails details = 2;
    private com.github.yeriomin.playstoreapi.MusicDetails details_ = com.github.yeriomin.playstoreapi.MusicDetails.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.MusicDetails, com.github.yeriomin.playstoreapi.MusicDetails.Builder, com.github.yeriomin.playstoreapi.MusicDetailsOrBuilder> detailsBuilder_;
    /**
     * <code>optional .MusicDetails details = 2;</code>
     */
    public boolean hasDetails() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .MusicDetails details = 2;</code>
     */
    public com.github.yeriomin.playstoreapi.MusicDetails getDetails() {
      if (detailsBuilder_ == null) {
        return details_;
      } else {
        return detailsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .MusicDetails details = 2;</code>
     */
    public Builder setDetails(com.github.yeriomin.playstoreapi.MusicDetails value) {
      if (detailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        details_ = value;
        onChanged();
      } else {
        detailsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .MusicDetails details = 2;</code>
     */
    public Builder setDetails(
        com.github.yeriomin.playstoreapi.MusicDetails.Builder builderForValue) {
      if (detailsBuilder_ == null) {
        details_ = builderForValue.build();
        onChanged();
      } else {
        detailsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .MusicDetails details = 2;</code>
     */
    public Builder mergeDetails(com.github.yeriomin.playstoreapi.MusicDetails value) {
      if (detailsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            details_ != com.github.yeriomin.playstoreapi.MusicDetails.getDefaultInstance()) {
          details_ =
            com.github.yeriomin.playstoreapi.MusicDetails.newBuilder(details_).mergeFrom(value).buildPartial();
        } else {
          details_ = value;
        }
        onChanged();
      } else {
        detailsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .MusicDetails details = 2;</code>
     */
    public Builder clearDetails() {
      if (detailsBuilder_ == null) {
        details_ = com.github.yeriomin.playstoreapi.MusicDetails.getDefaultInstance();
        onChanged();
      } else {
        detailsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .MusicDetails details = 2;</code>
     */
    public com.github.yeriomin.playstoreapi.MusicDetails.Builder getDetailsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getDetailsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .MusicDetails details = 2;</code>
     */
    public com.github.yeriomin.playstoreapi.MusicDetailsOrBuilder getDetailsOrBuilder() {
      if (detailsBuilder_ != null) {
        return detailsBuilder_.getMessageOrBuilder();
      } else {
        return details_;
      }
    }
    /**
     * <code>optional .MusicDetails details = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.MusicDetails, com.github.yeriomin.playstoreapi.MusicDetails.Builder, com.github.yeriomin.playstoreapi.MusicDetailsOrBuilder> 
        getDetailsFieldBuilder() {
      if (detailsBuilder_ == null) {
        detailsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.MusicDetails, com.github.yeriomin.playstoreapi.MusicDetails.Builder, com.github.yeriomin.playstoreapi.MusicDetailsOrBuilder>(
                details_,
                getParentForChildren(),
                isClean());
        details_ = null;
      }
      return detailsBuilder_;
    }

    // optional .ArtistDetails displayArtist = 3;
    private com.github.yeriomin.playstoreapi.ArtistDetails displayArtist_ = com.github.yeriomin.playstoreapi.ArtistDetails.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.ArtistDetails, com.github.yeriomin.playstoreapi.ArtistDetails.Builder, com.github.yeriomin.playstoreapi.ArtistDetailsOrBuilder> displayArtistBuilder_;
    /**
     * <code>optional .ArtistDetails displayArtist = 3;</code>
     */
    public boolean hasDisplayArtist() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .ArtistDetails displayArtist = 3;</code>
     */
    public com.github.yeriomin.playstoreapi.ArtistDetails getDisplayArtist() {
      if (displayArtistBuilder_ == null) {
        return displayArtist_;
      } else {
        return displayArtistBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ArtistDetails displayArtist = 3;</code>
     */
    public Builder setDisplayArtist(com.github.yeriomin.playstoreapi.ArtistDetails value) {
      if (displayArtistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        displayArtist_ = value;
        onChanged();
      } else {
        displayArtistBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .ArtistDetails displayArtist = 3;</code>
     */
    public Builder setDisplayArtist(
        com.github.yeriomin.playstoreapi.ArtistDetails.Builder builderForValue) {
      if (displayArtistBuilder_ == null) {
        displayArtist_ = builderForValue.build();
        onChanged();
      } else {
        displayArtistBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .ArtistDetails displayArtist = 3;</code>
     */
    public Builder mergeDisplayArtist(com.github.yeriomin.playstoreapi.ArtistDetails value) {
      if (displayArtistBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            displayArtist_ != com.github.yeriomin.playstoreapi.ArtistDetails.getDefaultInstance()) {
          displayArtist_ =
            com.github.yeriomin.playstoreapi.ArtistDetails.newBuilder(displayArtist_).mergeFrom(value).buildPartial();
        } else {
          displayArtist_ = value;
        }
        onChanged();
      } else {
        displayArtistBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .ArtistDetails displayArtist = 3;</code>
     */
    public Builder clearDisplayArtist() {
      if (displayArtistBuilder_ == null) {
        displayArtist_ = com.github.yeriomin.playstoreapi.ArtistDetails.getDefaultInstance();
        onChanged();
      } else {
        displayArtistBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .ArtistDetails displayArtist = 3;</code>
     */
    public com.github.yeriomin.playstoreapi.ArtistDetails.Builder getDisplayArtistBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getDisplayArtistFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ArtistDetails displayArtist = 3;</code>
     */
    public com.github.yeriomin.playstoreapi.ArtistDetailsOrBuilder getDisplayArtistOrBuilder() {
      if (displayArtistBuilder_ != null) {
        return displayArtistBuilder_.getMessageOrBuilder();
      } else {
        return displayArtist_;
      }
    }
    /**
     * <code>optional .ArtistDetails displayArtist = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.ArtistDetails, com.github.yeriomin.playstoreapi.ArtistDetails.Builder, com.github.yeriomin.playstoreapi.ArtistDetailsOrBuilder> 
        getDisplayArtistFieldBuilder() {
      if (displayArtistBuilder_ == null) {
        displayArtistBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.ArtistDetails, com.github.yeriomin.playstoreapi.ArtistDetails.Builder, com.github.yeriomin.playstoreapi.ArtistDetailsOrBuilder>(
                displayArtist_,
                getParentForChildren(),
                isClean());
        displayArtist_ = null;
      }
      return displayArtistBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:AlbumDetails)
  }

  static {
    defaultInstance = new AlbumDetails(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:AlbumDetails)
}

