// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface AndroidStatisticProtoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string tag = 1;
  /**
   * <code>optional string tag = 1;</code>
   */
  boolean hasTag();
  /**
   * <code>optional string tag = 1;</code>
   */
  java.lang.String getTag();
  /**
   * <code>optional string tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();

  // optional int32 count = 2;
  /**
   * <code>optional int32 count = 2;</code>
   */
  boolean hasCount();
  /**
   * <code>optional int32 count = 2;</code>
   */
  int getCount();

  // optional float sum = 3;
  /**
   * <code>optional float sum = 3;</code>
   */
  boolean hasSum();
  /**
   * <code>optional float sum = 3;</code>
   */
  float getSum();
}
