// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface AndroidCheckinRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string imei = 1;
  /**
   * <code>optional string imei = 1;</code>
   */
  boolean hasImei();
  /**
   * <code>optional string imei = 1;</code>
   */
  java.lang.String getImei();
  /**
   * <code>optional string imei = 1;</code>
   */
  com.google.protobuf.ByteString
      getImeiBytes();

  // optional int64 id = 2;
  /**
   * <code>optional int64 id = 2;</code>
   */
  boolean hasId();
  /**
   * <code>optional int64 id = 2;</code>
   */
  long getId();

  // optional string digest = 3;
  /**
   * <code>optional string digest = 3;</code>
   */
  boolean hasDigest();
  /**
   * <code>optional string digest = 3;</code>
   */
  java.lang.String getDigest();
  /**
   * <code>optional string digest = 3;</code>
   */
  com.google.protobuf.ByteString
      getDigestBytes();

  // optional .AndroidCheckinProto checkin = 4;
  /**
   * <code>optional .AndroidCheckinProto checkin = 4;</code>
   */
  boolean hasCheckin();
  /**
   * <code>optional .AndroidCheckinProto checkin = 4;</code>
   */
  com.github.yeriomin.playstoreapi.AndroidCheckinProto getCheckin();
  /**
   * <code>optional .AndroidCheckinProto checkin = 4;</code>
   */
  com.github.yeriomin.playstoreapi.AndroidCheckinProtoOrBuilder getCheckinOrBuilder();

  // optional string desiredBuild = 5;
  /**
   * <code>optional string desiredBuild = 5;</code>
   */
  boolean hasDesiredBuild();
  /**
   * <code>optional string desiredBuild = 5;</code>
   */
  java.lang.String getDesiredBuild();
  /**
   * <code>optional string desiredBuild = 5;</code>
   */
  com.google.protobuf.ByteString
      getDesiredBuildBytes();

  // optional string locale = 6;
  /**
   * <code>optional string locale = 6;</code>
   */
  boolean hasLocale();
  /**
   * <code>optional string locale = 6;</code>
   */
  java.lang.String getLocale();
  /**
   * <code>optional string locale = 6;</code>
   */
  com.google.protobuf.ByteString
      getLocaleBytes();

  // optional int64 loggingId = 7;
  /**
   * <code>optional int64 loggingId = 7;</code>
   */
  boolean hasLoggingId();
  /**
   * <code>optional int64 loggingId = 7;</code>
   */
  long getLoggingId();

  // optional string marketCheckin = 8;
  /**
   * <code>optional string marketCheckin = 8;</code>
   */
  boolean hasMarketCheckin();
  /**
   * <code>optional string marketCheckin = 8;</code>
   */
  java.lang.String getMarketCheckin();
  /**
   * <code>optional string marketCheckin = 8;</code>
   */
  com.google.protobuf.ByteString
      getMarketCheckinBytes();

  // repeated string macAddr = 9;
  /**
   * <code>repeated string macAddr = 9;</code>
   */
  java.util.List<java.lang.String>
  getMacAddrList();
  /**
   * <code>repeated string macAddr = 9;</code>
   */
  int getMacAddrCount();
  /**
   * <code>repeated string macAddr = 9;</code>
   */
  java.lang.String getMacAddr(int index);
  /**
   * <code>repeated string macAddr = 9;</code>
   */
  com.google.protobuf.ByteString
      getMacAddrBytes(int index);

  // optional string meid = 10;
  /**
   * <code>optional string meid = 10;</code>
   */
  boolean hasMeid();
  /**
   * <code>optional string meid = 10;</code>
   */
  java.lang.String getMeid();
  /**
   * <code>optional string meid = 10;</code>
   */
  com.google.protobuf.ByteString
      getMeidBytes();

  // repeated string accountCookie = 11;
  /**
   * <code>repeated string accountCookie = 11;</code>
   */
  java.util.List<java.lang.String>
  getAccountCookieList();
  /**
   * <code>repeated string accountCookie = 11;</code>
   */
  int getAccountCookieCount();
  /**
   * <code>repeated string accountCookie = 11;</code>
   */
  java.lang.String getAccountCookie(int index);
  /**
   * <code>repeated string accountCookie = 11;</code>
   */
  com.google.protobuf.ByteString
      getAccountCookieBytes(int index);

  // optional string timeZone = 12;
  /**
   * <code>optional string timeZone = 12;</code>
   */
  boolean hasTimeZone();
  /**
   * <code>optional string timeZone = 12;</code>
   */
  java.lang.String getTimeZone();
  /**
   * <code>optional string timeZone = 12;</code>
   */
  com.google.protobuf.ByteString
      getTimeZoneBytes();

  // optional fixed64 securityToken = 13;
  /**
   * <code>optional fixed64 securityToken = 13;</code>
   */
  boolean hasSecurityToken();
  /**
   * <code>optional fixed64 securityToken = 13;</code>
   */
  long getSecurityToken();

  // optional int32 version = 14;
  /**
   * <code>optional int32 version = 14;</code>
   */
  boolean hasVersion();
  /**
   * <code>optional int32 version = 14;</code>
   */
  int getVersion();

  // repeated string otaCert = 15;
  /**
   * <code>repeated string otaCert = 15;</code>
   */
  java.util.List<java.lang.String>
  getOtaCertList();
  /**
   * <code>repeated string otaCert = 15;</code>
   */
  int getOtaCertCount();
  /**
   * <code>repeated string otaCert = 15;</code>
   */
  java.lang.String getOtaCert(int index);
  /**
   * <code>repeated string otaCert = 15;</code>
   */
  com.google.protobuf.ByteString
      getOtaCertBytes(int index);

  // optional string serialNumber = 16;
  /**
   * <code>optional string serialNumber = 16;</code>
   */
  boolean hasSerialNumber();
  /**
   * <code>optional string serialNumber = 16;</code>
   */
  java.lang.String getSerialNumber();
  /**
   * <code>optional string serialNumber = 16;</code>
   */
  com.google.protobuf.ByteString
      getSerialNumberBytes();

  // optional string esn = 17;
  /**
   * <code>optional string esn = 17;</code>
   */
  boolean hasEsn();
  /**
   * <code>optional string esn = 17;</code>
   */
  java.lang.String getEsn();
  /**
   * <code>optional string esn = 17;</code>
   */
  com.google.protobuf.ByteString
      getEsnBytes();

  // optional .DeviceConfigurationProto deviceConfiguration = 18;
  /**
   * <code>optional .DeviceConfigurationProto deviceConfiguration = 18;</code>
   */
  boolean hasDeviceConfiguration();
  /**
   * <code>optional .DeviceConfigurationProto deviceConfiguration = 18;</code>
   */
  com.github.yeriomin.playstoreapi.DeviceConfigurationProto getDeviceConfiguration();
  /**
   * <code>optional .DeviceConfigurationProto deviceConfiguration = 18;</code>
   */
  com.github.yeriomin.playstoreapi.DeviceConfigurationProtoOrBuilder getDeviceConfigurationOrBuilder();

  // repeated string macAddrType = 19;
  /**
   * <code>repeated string macAddrType = 19;</code>
   */
  java.util.List<java.lang.String>
  getMacAddrTypeList();
  /**
   * <code>repeated string macAddrType = 19;</code>
   */
  int getMacAddrTypeCount();
  /**
   * <code>repeated string macAddrType = 19;</code>
   */
  java.lang.String getMacAddrType(int index);
  /**
   * <code>repeated string macAddrType = 19;</code>
   */
  com.google.protobuf.ByteString
      getMacAddrTypeBytes(int index);

  // optional int32 fragment = 20;
  /**
   * <code>optional int32 fragment = 20;</code>
   */
  boolean hasFragment();
  /**
   * <code>optional int32 fragment = 20;</code>
   */
  int getFragment();

  // optional string userName = 21;
  /**
   * <code>optional string userName = 21;</code>
   */
  boolean hasUserName();
  /**
   * <code>optional string userName = 21;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>optional string userName = 21;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  // optional int32 userSerialNumber = 22;
  /**
   * <code>optional int32 userSerialNumber = 22;</code>
   */
  boolean hasUserSerialNumber();
  /**
   * <code>optional int32 userSerialNumber = 22;</code>
   */
  int getUserSerialNumber();
}
