// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

/**
 * Protobuf type {@code AndroidAppDeliveryData}
 */
public  final class AndroidAppDeliveryData extends
    com.google.protobuf.GeneratedMessage
    implements AndroidAppDeliveryDataOrBuilder {
  // Use AndroidAppDeliveryData.newBuilder() to construct.
  private AndroidAppDeliveryData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private AndroidAppDeliveryData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final AndroidAppDeliveryData defaultInstance;
  public static AndroidAppDeliveryData getDefaultInstance() {
    return defaultInstance;
  }

  public AndroidAppDeliveryData getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private AndroidAppDeliveryData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            downloadSize_ = input.readInt64();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            signature_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            downloadUrl_ = input.readBytes();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              additionalFile_ = new java.util.ArrayList<com.github.yeriomin.playstoreapi.AppFileMetadata>();
              mutable_bitField0_ |= 0x00000008;
            }
            additionalFile_.add(input.readMessage(com.github.yeriomin.playstoreapi.AppFileMetadata.PARSER, extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              downloadAuthCookie_ = new java.util.ArrayList<com.github.yeriomin.playstoreapi.HttpCookie>();
              mutable_bitField0_ |= 0x00000010;
            }
            downloadAuthCookie_.add(input.readMessage(com.github.yeriomin.playstoreapi.HttpCookie.PARSER, extensionRegistry));
            break;
          }
          case 48: {
            bitField0_ |= 0x00000008;
            forwardLocked_ = input.readBool();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000010;
            refundTimeout_ = input.readInt64();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000020;
            serverInitiated_ = input.readBool();
            break;
          }
          case 72: {
            bitField0_ |= 0x00000040;
            postInstallRefundWindowMillis_ = input.readInt64();
            break;
          }
          case 80: {
            bitField0_ |= 0x00000080;
            immediateStartNeeded_ = input.readBool();
            break;
          }
          case 90: {
            com.github.yeriomin.playstoreapi.AndroidAppPatchData.Builder subBuilder = null;
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
              subBuilder = patchData_.toBuilder();
            }
            patchData_ = input.readMessage(com.github.yeriomin.playstoreapi.AndroidAppPatchData.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(patchData_);
              patchData_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000100;
            break;
          }
          case 98: {
            com.github.yeriomin.playstoreapi.EncryptionParams.Builder subBuilder = null;
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
              subBuilder = encryptionParams_.toBuilder();
            }
            encryptionParams_ = input.readMessage(com.github.yeriomin.playstoreapi.EncryptionParams.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(encryptionParams_);
              encryptionParams_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000200;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        additionalFile_ = java.util.Collections.unmodifiableList(additionalFile_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        downloadAuthCookie_ = java.util.Collections.unmodifiableList(downloadAuthCookie_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_AndroidAppDeliveryData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_AndroidAppDeliveryData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.yeriomin.playstoreapi.AndroidAppDeliveryData.class, com.github.yeriomin.playstoreapi.AndroidAppDeliveryData.Builder.class);
  }

  public static com.google.protobuf.Parser<AndroidAppDeliveryData> PARSER =
      new com.google.protobuf.AbstractParser<AndroidAppDeliveryData>() {
    public AndroidAppDeliveryData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AndroidAppDeliveryData(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<AndroidAppDeliveryData> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional int64 downloadSize = 1;
  public static final int DOWNLOADSIZE_FIELD_NUMBER = 1;
  private long downloadSize_;
  /**
   * <code>optional int64 downloadSize = 1;</code>
   */
  public boolean hasDownloadSize() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int64 downloadSize = 1;</code>
   */
  public long getDownloadSize() {
    return downloadSize_;
  }

  // optional string signature = 2;
  public static final int SIGNATURE_FIELD_NUMBER = 2;
  private java.lang.Object signature_;
  /**
   * <code>optional string signature = 2;</code>
   */
  public boolean hasSignature() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string signature = 2;</code>
   */
  public java.lang.String getSignature() {
    java.lang.Object ref = signature_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        signature_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string signature = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSignatureBytes() {
    java.lang.Object ref = signature_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signature_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string downloadUrl = 3;
  public static final int DOWNLOADURL_FIELD_NUMBER = 3;
  private java.lang.Object downloadUrl_;
  /**
   * <code>optional string downloadUrl = 3;</code>
   */
  public boolean hasDownloadUrl() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string downloadUrl = 3;</code>
   */
  public java.lang.String getDownloadUrl() {
    java.lang.Object ref = downloadUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        downloadUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string downloadUrl = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDownloadUrlBytes() {
    java.lang.Object ref = downloadUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      downloadUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // repeated .AppFileMetadata additionalFile = 4;
  public static final int ADDITIONALFILE_FIELD_NUMBER = 4;
  private java.util.List<com.github.yeriomin.playstoreapi.AppFileMetadata> additionalFile_;
  /**
   * <code>repeated .AppFileMetadata additionalFile = 4;</code>
   */
  public java.util.List<com.github.yeriomin.playstoreapi.AppFileMetadata> getAdditionalFileList() {
    return additionalFile_;
  }
  /**
   * <code>repeated .AppFileMetadata additionalFile = 4;</code>
   */
  public java.util.List<? extends com.github.yeriomin.playstoreapi.AppFileMetadataOrBuilder> 
      getAdditionalFileOrBuilderList() {
    return additionalFile_;
  }
  /**
   * <code>repeated .AppFileMetadata additionalFile = 4;</code>
   */
  public int getAdditionalFileCount() {
    return additionalFile_.size();
  }
  /**
   * <code>repeated .AppFileMetadata additionalFile = 4;</code>
   */
  public com.github.yeriomin.playstoreapi.AppFileMetadata getAdditionalFile(int index) {
    return additionalFile_.get(index);
  }
  /**
   * <code>repeated .AppFileMetadata additionalFile = 4;</code>
   */
  public com.github.yeriomin.playstoreapi.AppFileMetadataOrBuilder getAdditionalFileOrBuilder(
      int index) {
    return additionalFile_.get(index);
  }

  // repeated .HttpCookie downloadAuthCookie = 5;
  public static final int DOWNLOADAUTHCOOKIE_FIELD_NUMBER = 5;
  private java.util.List<com.github.yeriomin.playstoreapi.HttpCookie> downloadAuthCookie_;
  /**
   * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
   */
  public java.util.List<com.github.yeriomin.playstoreapi.HttpCookie> getDownloadAuthCookieList() {
    return downloadAuthCookie_;
  }
  /**
   * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
   */
  public java.util.List<? extends com.github.yeriomin.playstoreapi.HttpCookieOrBuilder> 
      getDownloadAuthCookieOrBuilderList() {
    return downloadAuthCookie_;
  }
  /**
   * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
   */
  public int getDownloadAuthCookieCount() {
    return downloadAuthCookie_.size();
  }
  /**
   * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
   */
  public com.github.yeriomin.playstoreapi.HttpCookie getDownloadAuthCookie(int index) {
    return downloadAuthCookie_.get(index);
  }
  /**
   * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
   */
  public com.github.yeriomin.playstoreapi.HttpCookieOrBuilder getDownloadAuthCookieOrBuilder(
      int index) {
    return downloadAuthCookie_.get(index);
  }

  // optional bool forwardLocked = 6;
  public static final int FORWARDLOCKED_FIELD_NUMBER = 6;
  private boolean forwardLocked_;
  /**
   * <code>optional bool forwardLocked = 6;</code>
   */
  public boolean hasForwardLocked() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional bool forwardLocked = 6;</code>
   */
  public boolean getForwardLocked() {
    return forwardLocked_;
  }

  // optional int64 refundTimeout = 7;
  public static final int REFUNDTIMEOUT_FIELD_NUMBER = 7;
  private long refundTimeout_;
  /**
   * <code>optional int64 refundTimeout = 7;</code>
   */
  public boolean hasRefundTimeout() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional int64 refundTimeout = 7;</code>
   */
  public long getRefundTimeout() {
    return refundTimeout_;
  }

  // optional bool serverInitiated = 8;
  public static final int SERVERINITIATED_FIELD_NUMBER = 8;
  private boolean serverInitiated_;
  /**
   * <code>optional bool serverInitiated = 8;</code>
   */
  public boolean hasServerInitiated() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional bool serverInitiated = 8;</code>
   */
  public boolean getServerInitiated() {
    return serverInitiated_;
  }

  // optional int64 postInstallRefundWindowMillis = 9;
  public static final int POSTINSTALLREFUNDWINDOWMILLIS_FIELD_NUMBER = 9;
  private long postInstallRefundWindowMillis_;
  /**
   * <code>optional int64 postInstallRefundWindowMillis = 9;</code>
   */
  public boolean hasPostInstallRefundWindowMillis() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional int64 postInstallRefundWindowMillis = 9;</code>
   */
  public long getPostInstallRefundWindowMillis() {
    return postInstallRefundWindowMillis_;
  }

  // optional bool immediateStartNeeded = 10;
  public static final int IMMEDIATESTARTNEEDED_FIELD_NUMBER = 10;
  private boolean immediateStartNeeded_;
  /**
   * <code>optional bool immediateStartNeeded = 10;</code>
   */
  public boolean hasImmediateStartNeeded() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional bool immediateStartNeeded = 10;</code>
   */
  public boolean getImmediateStartNeeded() {
    return immediateStartNeeded_;
  }

  // optional .AndroidAppPatchData patchData = 11;
  public static final int PATCHDATA_FIELD_NUMBER = 11;
  private com.github.yeriomin.playstoreapi.AndroidAppPatchData patchData_;
  /**
   * <code>optional .AndroidAppPatchData patchData = 11;</code>
   */
  public boolean hasPatchData() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional .AndroidAppPatchData patchData = 11;</code>
   */
  public com.github.yeriomin.playstoreapi.AndroidAppPatchData getPatchData() {
    return patchData_;
  }
  /**
   * <code>optional .AndroidAppPatchData patchData = 11;</code>
   */
  public com.github.yeriomin.playstoreapi.AndroidAppPatchDataOrBuilder getPatchDataOrBuilder() {
    return patchData_;
  }

  // optional .EncryptionParams encryptionParams = 12;
  public static final int ENCRYPTIONPARAMS_FIELD_NUMBER = 12;
  private com.github.yeriomin.playstoreapi.EncryptionParams encryptionParams_;
  /**
   * <code>optional .EncryptionParams encryptionParams = 12;</code>
   */
  public boolean hasEncryptionParams() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional .EncryptionParams encryptionParams = 12;</code>
   */
  public com.github.yeriomin.playstoreapi.EncryptionParams getEncryptionParams() {
    return encryptionParams_;
  }
  /**
   * <code>optional .EncryptionParams encryptionParams = 12;</code>
   */
  public com.github.yeriomin.playstoreapi.EncryptionParamsOrBuilder getEncryptionParamsOrBuilder() {
    return encryptionParams_;
  }

  private void initFields() {
    downloadSize_ = 0L;
    signature_ = "";
    downloadUrl_ = "";
    additionalFile_ = java.util.Collections.emptyList();
    downloadAuthCookie_ = java.util.Collections.emptyList();
    forwardLocked_ = false;
    refundTimeout_ = 0L;
    serverInitiated_ = false;
    postInstallRefundWindowMillis_ = 0L;
    immediateStartNeeded_ = false;
    patchData_ = com.github.yeriomin.playstoreapi.AndroidAppPatchData.getDefaultInstance();
    encryptionParams_ = com.github.yeriomin.playstoreapi.EncryptionParams.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, downloadSize_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getSignatureBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getDownloadUrlBytes());
    }
    for (int i = 0; i < additionalFile_.size(); i++) {
      output.writeMessage(4, additionalFile_.get(i));
    }
    for (int i = 0; i < downloadAuthCookie_.size(); i++) {
      output.writeMessage(5, downloadAuthCookie_.get(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBool(6, forwardLocked_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt64(7, refundTimeout_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBool(8, serverInitiated_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeInt64(9, postInstallRefundWindowMillis_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeBool(10, immediateStartNeeded_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeMessage(11, patchData_);
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeMessage(12, encryptionParams_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, downloadSize_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getSignatureBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getDownloadUrlBytes());
    }
    for (int i = 0; i < additionalFile_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, additionalFile_.get(i));
    }
    for (int i = 0; i < downloadAuthCookie_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, downloadAuthCookie_.get(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, forwardLocked_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, refundTimeout_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, serverInitiated_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, postInstallRefundWindowMillis_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, immediateStartNeeded_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, patchData_);
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, encryptionParams_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.github.yeriomin.playstoreapi.AndroidAppDeliveryData prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AndroidAppDeliveryData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.github.yeriomin.playstoreapi.AndroidAppDeliveryDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_AndroidAppDeliveryData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_AndroidAppDeliveryData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.yeriomin.playstoreapi.AndroidAppDeliveryData.class, com.github.yeriomin.playstoreapi.AndroidAppDeliveryData.Builder.class);
    }

    // Construct using com.github.yeriomin.playstoreapi.AndroidAppDeliveryData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getAdditionalFileFieldBuilder();
        getDownloadAuthCookieFieldBuilder();
        getPatchDataFieldBuilder();
        getEncryptionParamsFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      downloadSize_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      signature_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      downloadUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      if (additionalFileBuilder_ == null) {
        additionalFile_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        additionalFileBuilder_.clear();
      }
      if (downloadAuthCookieBuilder_ == null) {
        downloadAuthCookie_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        downloadAuthCookieBuilder_.clear();
      }
      forwardLocked_ = false;
      bitField0_ = (bitField0_ & ~0x00000020);
      refundTimeout_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      serverInitiated_ = false;
      bitField0_ = (bitField0_ & ~0x00000080);
      postInstallRefundWindowMillis_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000100);
      immediateStartNeeded_ = false;
      bitField0_ = (bitField0_ & ~0x00000200);
      if (patchDataBuilder_ == null) {
        patchData_ = com.github.yeriomin.playstoreapi.AndroidAppPatchData.getDefaultInstance();
      } else {
        patchDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000400);
      if (encryptionParamsBuilder_ == null) {
        encryptionParams_ = com.github.yeriomin.playstoreapi.EncryptionParams.getDefaultInstance();
      } else {
        encryptionParamsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000800);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_AndroidAppDeliveryData_descriptor;
    }

    public com.github.yeriomin.playstoreapi.AndroidAppDeliveryData getDefaultInstanceForType() {
      return com.github.yeriomin.playstoreapi.AndroidAppDeliveryData.getDefaultInstance();
    }

    public com.github.yeriomin.playstoreapi.AndroidAppDeliveryData build() {
      com.github.yeriomin.playstoreapi.AndroidAppDeliveryData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.yeriomin.playstoreapi.AndroidAppDeliveryData buildPartial() {
      com.github.yeriomin.playstoreapi.AndroidAppDeliveryData result = new com.github.yeriomin.playstoreapi.AndroidAppDeliveryData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.downloadSize_ = downloadSize_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.signature_ = signature_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.downloadUrl_ = downloadUrl_;
      if (additionalFileBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          additionalFile_ = java.util.Collections.unmodifiableList(additionalFile_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.additionalFile_ = additionalFile_;
      } else {
        result.additionalFile_ = additionalFileBuilder_.build();
      }
      if (downloadAuthCookieBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          downloadAuthCookie_ = java.util.Collections.unmodifiableList(downloadAuthCookie_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.downloadAuthCookie_ = downloadAuthCookie_;
      } else {
        result.downloadAuthCookie_ = downloadAuthCookieBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000008;
      }
      result.forwardLocked_ = forwardLocked_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000010;
      }
      result.refundTimeout_ = refundTimeout_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000020;
      }
      result.serverInitiated_ = serverInitiated_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000040;
      }
      result.postInstallRefundWindowMillis_ = postInstallRefundWindowMillis_;
      if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
        to_bitField0_ |= 0x00000080;
      }
      result.immediateStartNeeded_ = immediateStartNeeded_;
      if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
        to_bitField0_ |= 0x00000100;
      }
      if (patchDataBuilder_ == null) {
        result.patchData_ = patchData_;
      } else {
        result.patchData_ = patchDataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
        to_bitField0_ |= 0x00000200;
      }
      if (encryptionParamsBuilder_ == null) {
        result.encryptionParams_ = encryptionParams_;
      } else {
        result.encryptionParams_ = encryptionParamsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.yeriomin.playstoreapi.AndroidAppDeliveryData) {
        return mergeFrom((com.github.yeriomin.playstoreapi.AndroidAppDeliveryData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.yeriomin.playstoreapi.AndroidAppDeliveryData other) {
      if (other == com.github.yeriomin.playstoreapi.AndroidAppDeliveryData.getDefaultInstance()) return this;
      if (other.hasDownloadSize()) {
        setDownloadSize(other.getDownloadSize());
      }
      if (other.hasSignature()) {
        bitField0_ |= 0x00000002;
        signature_ = other.signature_;
        onChanged();
      }
      if (other.hasDownloadUrl()) {
        bitField0_ |= 0x00000004;
        downloadUrl_ = other.downloadUrl_;
        onChanged();
      }
      if (additionalFileBuilder_ == null) {
        if (!other.additionalFile_.isEmpty()) {
          if (additionalFile_.isEmpty()) {
            additionalFile_ = other.additionalFile_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAdditionalFileIsMutable();
            additionalFile_.addAll(other.additionalFile_);
          }
          onChanged();
        }
      } else {
        if (!other.additionalFile_.isEmpty()) {
          if (additionalFileBuilder_.isEmpty()) {
            additionalFileBuilder_.dispose();
            additionalFileBuilder_ = null;
            additionalFile_ = other.additionalFile_;
            bitField0_ = (bitField0_ & ~0x00000008);
            additionalFileBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getAdditionalFileFieldBuilder() : null;
          } else {
            additionalFileBuilder_.addAllMessages(other.additionalFile_);
          }
        }
      }
      if (downloadAuthCookieBuilder_ == null) {
        if (!other.downloadAuthCookie_.isEmpty()) {
          if (downloadAuthCookie_.isEmpty()) {
            downloadAuthCookie_ = other.downloadAuthCookie_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDownloadAuthCookieIsMutable();
            downloadAuthCookie_.addAll(other.downloadAuthCookie_);
          }
          onChanged();
        }
      } else {
        if (!other.downloadAuthCookie_.isEmpty()) {
          if (downloadAuthCookieBuilder_.isEmpty()) {
            downloadAuthCookieBuilder_.dispose();
            downloadAuthCookieBuilder_ = null;
            downloadAuthCookie_ = other.downloadAuthCookie_;
            bitField0_ = (bitField0_ & ~0x00000010);
            downloadAuthCookieBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getDownloadAuthCookieFieldBuilder() : null;
          } else {
            downloadAuthCookieBuilder_.addAllMessages(other.downloadAuthCookie_);
          }
        }
      }
      if (other.hasForwardLocked()) {
        setForwardLocked(other.getForwardLocked());
      }
      if (other.hasRefundTimeout()) {
        setRefundTimeout(other.getRefundTimeout());
      }
      if (other.hasServerInitiated()) {
        setServerInitiated(other.getServerInitiated());
      }
      if (other.hasPostInstallRefundWindowMillis()) {
        setPostInstallRefundWindowMillis(other.getPostInstallRefundWindowMillis());
      }
      if (other.hasImmediateStartNeeded()) {
        setImmediateStartNeeded(other.getImmediateStartNeeded());
      }
      if (other.hasPatchData()) {
        mergePatchData(other.getPatchData());
      }
      if (other.hasEncryptionParams()) {
        mergeEncryptionParams(other.getEncryptionParams());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.yeriomin.playstoreapi.AndroidAppDeliveryData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.yeriomin.playstoreapi.AndroidAppDeliveryData) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional int64 downloadSize = 1;
    private long downloadSize_ ;
    /**
     * <code>optional int64 downloadSize = 1;</code>
     */
    public boolean hasDownloadSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 downloadSize = 1;</code>
     */
    public long getDownloadSize() {
      return downloadSize_;
    }
    /**
     * <code>optional int64 downloadSize = 1;</code>
     */
    public Builder setDownloadSize(long value) {
      bitField0_ |= 0x00000001;
      downloadSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 downloadSize = 1;</code>
     */
    public Builder clearDownloadSize() {
      bitField0_ = (bitField0_ & ~0x00000001);
      downloadSize_ = 0L;
      onChanged();
      return this;
    }

    // optional string signature = 2;
    private java.lang.Object signature_ = "";
    /**
     * <code>optional string signature = 2;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string signature = 2;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        signature_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string signature = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string signature = 2;</code>
     */
    public Builder setSignature(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      signature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string signature = 2;</code>
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000002);
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }
    /**
     * <code>optional string signature = 2;</code>
     */
    public Builder setSignatureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      signature_ = value;
      onChanged();
      return this;
    }

    // optional string downloadUrl = 3;
    private java.lang.Object downloadUrl_ = "";
    /**
     * <code>optional string downloadUrl = 3;</code>
     */
    public boolean hasDownloadUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string downloadUrl = 3;</code>
     */
    public java.lang.String getDownloadUrl() {
      java.lang.Object ref = downloadUrl_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        downloadUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string downloadUrl = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDownloadUrlBytes() {
      java.lang.Object ref = downloadUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        downloadUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string downloadUrl = 3;</code>
     */
    public Builder setDownloadUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      downloadUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string downloadUrl = 3;</code>
     */
    public Builder clearDownloadUrl() {
      bitField0_ = (bitField0_ & ~0x00000004);
      downloadUrl_ = getDefaultInstance().getDownloadUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string downloadUrl = 3;</code>
     */
    public Builder setDownloadUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      downloadUrl_ = value;
      onChanged();
      return this;
    }

    // repeated .AppFileMetadata additionalFile = 4;
    private java.util.List<com.github.yeriomin.playstoreapi.AppFileMetadata> additionalFile_ =
      java.util.Collections.emptyList();
    private void ensureAdditionalFileIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        additionalFile_ = new java.util.ArrayList<com.github.yeriomin.playstoreapi.AppFileMetadata>(additionalFile_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.yeriomin.playstoreapi.AppFileMetadata, com.github.yeriomin.playstoreapi.AppFileMetadata.Builder, com.github.yeriomin.playstoreapi.AppFileMetadataOrBuilder> additionalFileBuilder_;

    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public java.util.List<com.github.yeriomin.playstoreapi.AppFileMetadata> getAdditionalFileList() {
      if (additionalFileBuilder_ == null) {
        return java.util.Collections.unmodifiableList(additionalFile_);
      } else {
        return additionalFileBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public int getAdditionalFileCount() {
      if (additionalFileBuilder_ == null) {
        return additionalFile_.size();
      } else {
        return additionalFileBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public com.github.yeriomin.playstoreapi.AppFileMetadata getAdditionalFile(int index) {
      if (additionalFileBuilder_ == null) {
        return additionalFile_.get(index);
      } else {
        return additionalFileBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public Builder setAdditionalFile(
        int index, com.github.yeriomin.playstoreapi.AppFileMetadata value) {
      if (additionalFileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdditionalFileIsMutable();
        additionalFile_.set(index, value);
        onChanged();
      } else {
        additionalFileBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public Builder setAdditionalFile(
        int index, com.github.yeriomin.playstoreapi.AppFileMetadata.Builder builderForValue) {
      if (additionalFileBuilder_ == null) {
        ensureAdditionalFileIsMutable();
        additionalFile_.set(index, builderForValue.build());
        onChanged();
      } else {
        additionalFileBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public Builder addAdditionalFile(com.github.yeriomin.playstoreapi.AppFileMetadata value) {
      if (additionalFileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdditionalFileIsMutable();
        additionalFile_.add(value);
        onChanged();
      } else {
        additionalFileBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public Builder addAdditionalFile(
        int index, com.github.yeriomin.playstoreapi.AppFileMetadata value) {
      if (additionalFileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdditionalFileIsMutable();
        additionalFile_.add(index, value);
        onChanged();
      } else {
        additionalFileBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public Builder addAdditionalFile(
        com.github.yeriomin.playstoreapi.AppFileMetadata.Builder builderForValue) {
      if (additionalFileBuilder_ == null) {
        ensureAdditionalFileIsMutable();
        additionalFile_.add(builderForValue.build());
        onChanged();
      } else {
        additionalFileBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public Builder addAdditionalFile(
        int index, com.github.yeriomin.playstoreapi.AppFileMetadata.Builder builderForValue) {
      if (additionalFileBuilder_ == null) {
        ensureAdditionalFileIsMutable();
        additionalFile_.add(index, builderForValue.build());
        onChanged();
      } else {
        additionalFileBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public Builder addAllAdditionalFile(
        java.lang.Iterable<? extends com.github.yeriomin.playstoreapi.AppFileMetadata> values) {
      if (additionalFileBuilder_ == null) {
        ensureAdditionalFileIsMutable();
        super.addAll(values, additionalFile_);
        onChanged();
      } else {
        additionalFileBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public Builder clearAdditionalFile() {
      if (additionalFileBuilder_ == null) {
        additionalFile_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        additionalFileBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public Builder removeAdditionalFile(int index) {
      if (additionalFileBuilder_ == null) {
        ensureAdditionalFileIsMutable();
        additionalFile_.remove(index);
        onChanged();
      } else {
        additionalFileBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public com.github.yeriomin.playstoreapi.AppFileMetadata.Builder getAdditionalFileBuilder(
        int index) {
      return getAdditionalFileFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public com.github.yeriomin.playstoreapi.AppFileMetadataOrBuilder getAdditionalFileOrBuilder(
        int index) {
      if (additionalFileBuilder_ == null) {
        return additionalFile_.get(index);  } else {
        return additionalFileBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public java.util.List<? extends com.github.yeriomin.playstoreapi.AppFileMetadataOrBuilder> 
         getAdditionalFileOrBuilderList() {
      if (additionalFileBuilder_ != null) {
        return additionalFileBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(additionalFile_);
      }
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public com.github.yeriomin.playstoreapi.AppFileMetadata.Builder addAdditionalFileBuilder() {
      return getAdditionalFileFieldBuilder().addBuilder(
          com.github.yeriomin.playstoreapi.AppFileMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public com.github.yeriomin.playstoreapi.AppFileMetadata.Builder addAdditionalFileBuilder(
        int index) {
      return getAdditionalFileFieldBuilder().addBuilder(
          index, com.github.yeriomin.playstoreapi.AppFileMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .AppFileMetadata additionalFile = 4;</code>
     */
    public java.util.List<com.github.yeriomin.playstoreapi.AppFileMetadata.Builder> 
         getAdditionalFileBuilderList() {
      return getAdditionalFileFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.yeriomin.playstoreapi.AppFileMetadata, com.github.yeriomin.playstoreapi.AppFileMetadata.Builder, com.github.yeriomin.playstoreapi.AppFileMetadataOrBuilder> 
        getAdditionalFileFieldBuilder() {
      if (additionalFileBuilder_ == null) {
        additionalFileBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.github.yeriomin.playstoreapi.AppFileMetadata, com.github.yeriomin.playstoreapi.AppFileMetadata.Builder, com.github.yeriomin.playstoreapi.AppFileMetadataOrBuilder>(
                additionalFile_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        additionalFile_ = null;
      }
      return additionalFileBuilder_;
    }

    // repeated .HttpCookie downloadAuthCookie = 5;
    private java.util.List<com.github.yeriomin.playstoreapi.HttpCookie> downloadAuthCookie_ =
      java.util.Collections.emptyList();
    private void ensureDownloadAuthCookieIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        downloadAuthCookie_ = new java.util.ArrayList<com.github.yeriomin.playstoreapi.HttpCookie>(downloadAuthCookie_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.yeriomin.playstoreapi.HttpCookie, com.github.yeriomin.playstoreapi.HttpCookie.Builder, com.github.yeriomin.playstoreapi.HttpCookieOrBuilder> downloadAuthCookieBuilder_;

    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public java.util.List<com.github.yeriomin.playstoreapi.HttpCookie> getDownloadAuthCookieList() {
      if (downloadAuthCookieBuilder_ == null) {
        return java.util.Collections.unmodifiableList(downloadAuthCookie_);
      } else {
        return downloadAuthCookieBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public int getDownloadAuthCookieCount() {
      if (downloadAuthCookieBuilder_ == null) {
        return downloadAuthCookie_.size();
      } else {
        return downloadAuthCookieBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public com.github.yeriomin.playstoreapi.HttpCookie getDownloadAuthCookie(int index) {
      if (downloadAuthCookieBuilder_ == null) {
        return downloadAuthCookie_.get(index);
      } else {
        return downloadAuthCookieBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public Builder setDownloadAuthCookie(
        int index, com.github.yeriomin.playstoreapi.HttpCookie value) {
      if (downloadAuthCookieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDownloadAuthCookieIsMutable();
        downloadAuthCookie_.set(index, value);
        onChanged();
      } else {
        downloadAuthCookieBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public Builder setDownloadAuthCookie(
        int index, com.github.yeriomin.playstoreapi.HttpCookie.Builder builderForValue) {
      if (downloadAuthCookieBuilder_ == null) {
        ensureDownloadAuthCookieIsMutable();
        downloadAuthCookie_.set(index, builderForValue.build());
        onChanged();
      } else {
        downloadAuthCookieBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public Builder addDownloadAuthCookie(com.github.yeriomin.playstoreapi.HttpCookie value) {
      if (downloadAuthCookieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDownloadAuthCookieIsMutable();
        downloadAuthCookie_.add(value);
        onChanged();
      } else {
        downloadAuthCookieBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public Builder addDownloadAuthCookie(
        int index, com.github.yeriomin.playstoreapi.HttpCookie value) {
      if (downloadAuthCookieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDownloadAuthCookieIsMutable();
        downloadAuthCookie_.add(index, value);
        onChanged();
      } else {
        downloadAuthCookieBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public Builder addDownloadAuthCookie(
        com.github.yeriomin.playstoreapi.HttpCookie.Builder builderForValue) {
      if (downloadAuthCookieBuilder_ == null) {
        ensureDownloadAuthCookieIsMutable();
        downloadAuthCookie_.add(builderForValue.build());
        onChanged();
      } else {
        downloadAuthCookieBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public Builder addDownloadAuthCookie(
        int index, com.github.yeriomin.playstoreapi.HttpCookie.Builder builderForValue) {
      if (downloadAuthCookieBuilder_ == null) {
        ensureDownloadAuthCookieIsMutable();
        downloadAuthCookie_.add(index, builderForValue.build());
        onChanged();
      } else {
        downloadAuthCookieBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public Builder addAllDownloadAuthCookie(
        java.lang.Iterable<? extends com.github.yeriomin.playstoreapi.HttpCookie> values) {
      if (downloadAuthCookieBuilder_ == null) {
        ensureDownloadAuthCookieIsMutable();
        super.addAll(values, downloadAuthCookie_);
        onChanged();
      } else {
        downloadAuthCookieBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public Builder clearDownloadAuthCookie() {
      if (downloadAuthCookieBuilder_ == null) {
        downloadAuthCookie_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        downloadAuthCookieBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public Builder removeDownloadAuthCookie(int index) {
      if (downloadAuthCookieBuilder_ == null) {
        ensureDownloadAuthCookieIsMutable();
        downloadAuthCookie_.remove(index);
        onChanged();
      } else {
        downloadAuthCookieBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public com.github.yeriomin.playstoreapi.HttpCookie.Builder getDownloadAuthCookieBuilder(
        int index) {
      return getDownloadAuthCookieFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public com.github.yeriomin.playstoreapi.HttpCookieOrBuilder getDownloadAuthCookieOrBuilder(
        int index) {
      if (downloadAuthCookieBuilder_ == null) {
        return downloadAuthCookie_.get(index);  } else {
        return downloadAuthCookieBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public java.util.List<? extends com.github.yeriomin.playstoreapi.HttpCookieOrBuilder> 
         getDownloadAuthCookieOrBuilderList() {
      if (downloadAuthCookieBuilder_ != null) {
        return downloadAuthCookieBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(downloadAuthCookie_);
      }
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public com.github.yeriomin.playstoreapi.HttpCookie.Builder addDownloadAuthCookieBuilder() {
      return getDownloadAuthCookieFieldBuilder().addBuilder(
          com.github.yeriomin.playstoreapi.HttpCookie.getDefaultInstance());
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public com.github.yeriomin.playstoreapi.HttpCookie.Builder addDownloadAuthCookieBuilder(
        int index) {
      return getDownloadAuthCookieFieldBuilder().addBuilder(
          index, com.github.yeriomin.playstoreapi.HttpCookie.getDefaultInstance());
    }
    /**
     * <code>repeated .HttpCookie downloadAuthCookie = 5;</code>
     */
    public java.util.List<com.github.yeriomin.playstoreapi.HttpCookie.Builder> 
         getDownloadAuthCookieBuilderList() {
      return getDownloadAuthCookieFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.yeriomin.playstoreapi.HttpCookie, com.github.yeriomin.playstoreapi.HttpCookie.Builder, com.github.yeriomin.playstoreapi.HttpCookieOrBuilder> 
        getDownloadAuthCookieFieldBuilder() {
      if (downloadAuthCookieBuilder_ == null) {
        downloadAuthCookieBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.github.yeriomin.playstoreapi.HttpCookie, com.github.yeriomin.playstoreapi.HttpCookie.Builder, com.github.yeriomin.playstoreapi.HttpCookieOrBuilder>(
                downloadAuthCookie_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        downloadAuthCookie_ = null;
      }
      return downloadAuthCookieBuilder_;
    }

    // optional bool forwardLocked = 6;
    private boolean forwardLocked_ ;
    /**
     * <code>optional bool forwardLocked = 6;</code>
     */
    public boolean hasForwardLocked() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool forwardLocked = 6;</code>
     */
    public boolean getForwardLocked() {
      return forwardLocked_;
    }
    /**
     * <code>optional bool forwardLocked = 6;</code>
     */
    public Builder setForwardLocked(boolean value) {
      bitField0_ |= 0x00000020;
      forwardLocked_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool forwardLocked = 6;</code>
     */
    public Builder clearForwardLocked() {
      bitField0_ = (bitField0_ & ~0x00000020);
      forwardLocked_ = false;
      onChanged();
      return this;
    }

    // optional int64 refundTimeout = 7;
    private long refundTimeout_ ;
    /**
     * <code>optional int64 refundTimeout = 7;</code>
     */
    public boolean hasRefundTimeout() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 refundTimeout = 7;</code>
     */
    public long getRefundTimeout() {
      return refundTimeout_;
    }
    /**
     * <code>optional int64 refundTimeout = 7;</code>
     */
    public Builder setRefundTimeout(long value) {
      bitField0_ |= 0x00000040;
      refundTimeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 refundTimeout = 7;</code>
     */
    public Builder clearRefundTimeout() {
      bitField0_ = (bitField0_ & ~0x00000040);
      refundTimeout_ = 0L;
      onChanged();
      return this;
    }

    // optional bool serverInitiated = 8;
    private boolean serverInitiated_ ;
    /**
     * <code>optional bool serverInitiated = 8;</code>
     */
    public boolean hasServerInitiated() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bool serverInitiated = 8;</code>
     */
    public boolean getServerInitiated() {
      return serverInitiated_;
    }
    /**
     * <code>optional bool serverInitiated = 8;</code>
     */
    public Builder setServerInitiated(boolean value) {
      bitField0_ |= 0x00000080;
      serverInitiated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool serverInitiated = 8;</code>
     */
    public Builder clearServerInitiated() {
      bitField0_ = (bitField0_ & ~0x00000080);
      serverInitiated_ = false;
      onChanged();
      return this;
    }

    // optional int64 postInstallRefundWindowMillis = 9;
    private long postInstallRefundWindowMillis_ ;
    /**
     * <code>optional int64 postInstallRefundWindowMillis = 9;</code>
     */
    public boolean hasPostInstallRefundWindowMillis() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 postInstallRefundWindowMillis = 9;</code>
     */
    public long getPostInstallRefundWindowMillis() {
      return postInstallRefundWindowMillis_;
    }
    /**
     * <code>optional int64 postInstallRefundWindowMillis = 9;</code>
     */
    public Builder setPostInstallRefundWindowMillis(long value) {
      bitField0_ |= 0x00000100;
      postInstallRefundWindowMillis_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 postInstallRefundWindowMillis = 9;</code>
     */
    public Builder clearPostInstallRefundWindowMillis() {
      bitField0_ = (bitField0_ & ~0x00000100);
      postInstallRefundWindowMillis_ = 0L;
      onChanged();
      return this;
    }

    // optional bool immediateStartNeeded = 10;
    private boolean immediateStartNeeded_ ;
    /**
     * <code>optional bool immediateStartNeeded = 10;</code>
     */
    public boolean hasImmediateStartNeeded() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional bool immediateStartNeeded = 10;</code>
     */
    public boolean getImmediateStartNeeded() {
      return immediateStartNeeded_;
    }
    /**
     * <code>optional bool immediateStartNeeded = 10;</code>
     */
    public Builder setImmediateStartNeeded(boolean value) {
      bitField0_ |= 0x00000200;
      immediateStartNeeded_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool immediateStartNeeded = 10;</code>
     */
    public Builder clearImmediateStartNeeded() {
      bitField0_ = (bitField0_ & ~0x00000200);
      immediateStartNeeded_ = false;
      onChanged();
      return this;
    }

    // optional .AndroidAppPatchData patchData = 11;
    private com.github.yeriomin.playstoreapi.AndroidAppPatchData patchData_ = com.github.yeriomin.playstoreapi.AndroidAppPatchData.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.AndroidAppPatchData, com.github.yeriomin.playstoreapi.AndroidAppPatchData.Builder, com.github.yeriomin.playstoreapi.AndroidAppPatchDataOrBuilder> patchDataBuilder_;
    /**
     * <code>optional .AndroidAppPatchData patchData = 11;</code>
     */
    public boolean hasPatchData() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional .AndroidAppPatchData patchData = 11;</code>
     */
    public com.github.yeriomin.playstoreapi.AndroidAppPatchData getPatchData() {
      if (patchDataBuilder_ == null) {
        return patchData_;
      } else {
        return patchDataBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .AndroidAppPatchData patchData = 11;</code>
     */
    public Builder setPatchData(com.github.yeriomin.playstoreapi.AndroidAppPatchData value) {
      if (patchDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        patchData_ = value;
        onChanged();
      } else {
        patchDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <code>optional .AndroidAppPatchData patchData = 11;</code>
     */
    public Builder setPatchData(
        com.github.yeriomin.playstoreapi.AndroidAppPatchData.Builder builderForValue) {
      if (patchDataBuilder_ == null) {
        patchData_ = builderForValue.build();
        onChanged();
      } else {
        patchDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <code>optional .AndroidAppPatchData patchData = 11;</code>
     */
    public Builder mergePatchData(com.github.yeriomin.playstoreapi.AndroidAppPatchData value) {
      if (patchDataBuilder_ == null) {
        if (((bitField0_ & 0x00000400) == 0x00000400) &&
            patchData_ != com.github.yeriomin.playstoreapi.AndroidAppPatchData.getDefaultInstance()) {
          patchData_ =
            com.github.yeriomin.playstoreapi.AndroidAppPatchData.newBuilder(patchData_).mergeFrom(value).buildPartial();
        } else {
          patchData_ = value;
        }
        onChanged();
      } else {
        patchDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <code>optional .AndroidAppPatchData patchData = 11;</code>
     */
    public Builder clearPatchData() {
      if (patchDataBuilder_ == null) {
        patchData_ = com.github.yeriomin.playstoreapi.AndroidAppPatchData.getDefaultInstance();
        onChanged();
      } else {
        patchDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000400);
      return this;
    }
    /**
     * <code>optional .AndroidAppPatchData patchData = 11;</code>
     */
    public com.github.yeriomin.playstoreapi.AndroidAppPatchData.Builder getPatchDataBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getPatchDataFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .AndroidAppPatchData patchData = 11;</code>
     */
    public com.github.yeriomin.playstoreapi.AndroidAppPatchDataOrBuilder getPatchDataOrBuilder() {
      if (patchDataBuilder_ != null) {
        return patchDataBuilder_.getMessageOrBuilder();
      } else {
        return patchData_;
      }
    }
    /**
     * <code>optional .AndroidAppPatchData patchData = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.AndroidAppPatchData, com.github.yeriomin.playstoreapi.AndroidAppPatchData.Builder, com.github.yeriomin.playstoreapi.AndroidAppPatchDataOrBuilder> 
        getPatchDataFieldBuilder() {
      if (patchDataBuilder_ == null) {
        patchDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.AndroidAppPatchData, com.github.yeriomin.playstoreapi.AndroidAppPatchData.Builder, com.github.yeriomin.playstoreapi.AndroidAppPatchDataOrBuilder>(
                patchData_,
                getParentForChildren(),
                isClean());
        patchData_ = null;
      }
      return patchDataBuilder_;
    }

    // optional .EncryptionParams encryptionParams = 12;
    private com.github.yeriomin.playstoreapi.EncryptionParams encryptionParams_ = com.github.yeriomin.playstoreapi.EncryptionParams.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.EncryptionParams, com.github.yeriomin.playstoreapi.EncryptionParams.Builder, com.github.yeriomin.playstoreapi.EncryptionParamsOrBuilder> encryptionParamsBuilder_;
    /**
     * <code>optional .EncryptionParams encryptionParams = 12;</code>
     */
    public boolean hasEncryptionParams() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional .EncryptionParams encryptionParams = 12;</code>
     */
    public com.github.yeriomin.playstoreapi.EncryptionParams getEncryptionParams() {
      if (encryptionParamsBuilder_ == null) {
        return encryptionParams_;
      } else {
        return encryptionParamsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .EncryptionParams encryptionParams = 12;</code>
     */
    public Builder setEncryptionParams(com.github.yeriomin.playstoreapi.EncryptionParams value) {
      if (encryptionParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        encryptionParams_ = value;
        onChanged();
      } else {
        encryptionParamsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      return this;
    }
    /**
     * <code>optional .EncryptionParams encryptionParams = 12;</code>
     */
    public Builder setEncryptionParams(
        com.github.yeriomin.playstoreapi.EncryptionParams.Builder builderForValue) {
      if (encryptionParamsBuilder_ == null) {
        encryptionParams_ = builderForValue.build();
        onChanged();
      } else {
        encryptionParamsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      return this;
    }
    /**
     * <code>optional .EncryptionParams encryptionParams = 12;</code>
     */
    public Builder mergeEncryptionParams(com.github.yeriomin.playstoreapi.EncryptionParams value) {
      if (encryptionParamsBuilder_ == null) {
        if (((bitField0_ & 0x00000800) == 0x00000800) &&
            encryptionParams_ != com.github.yeriomin.playstoreapi.EncryptionParams.getDefaultInstance()) {
          encryptionParams_ =
            com.github.yeriomin.playstoreapi.EncryptionParams.newBuilder(encryptionParams_).mergeFrom(value).buildPartial();
        } else {
          encryptionParams_ = value;
        }
        onChanged();
      } else {
        encryptionParamsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000800;
      return this;
    }
    /**
     * <code>optional .EncryptionParams encryptionParams = 12;</code>
     */
    public Builder clearEncryptionParams() {
      if (encryptionParamsBuilder_ == null) {
        encryptionParams_ = com.github.yeriomin.playstoreapi.EncryptionParams.getDefaultInstance();
        onChanged();
      } else {
        encryptionParamsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000800);
      return this;
    }
    /**
     * <code>optional .EncryptionParams encryptionParams = 12;</code>
     */
    public com.github.yeriomin.playstoreapi.EncryptionParams.Builder getEncryptionParamsBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getEncryptionParamsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .EncryptionParams encryptionParams = 12;</code>
     */
    public com.github.yeriomin.playstoreapi.EncryptionParamsOrBuilder getEncryptionParamsOrBuilder() {
      if (encryptionParamsBuilder_ != null) {
        return encryptionParamsBuilder_.getMessageOrBuilder();
      } else {
        return encryptionParams_;
      }
    }
    /**
     * <code>optional .EncryptionParams encryptionParams = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.EncryptionParams, com.github.yeriomin.playstoreapi.EncryptionParams.Builder, com.github.yeriomin.playstoreapi.EncryptionParamsOrBuilder> 
        getEncryptionParamsFieldBuilder() {
      if (encryptionParamsBuilder_ == null) {
        encryptionParamsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.EncryptionParams, com.github.yeriomin.playstoreapi.EncryptionParams.Builder, com.github.yeriomin.playstoreapi.EncryptionParamsOrBuilder>(
                encryptionParams_,
                getParentForChildren(),
                isClean());
        encryptionParams_ = null;
      }
      return encryptionParamsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:AndroidAppDeliveryData)
  }

  static {
    defaultInstance = new AndroidAppDeliveryData(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:AndroidAppDeliveryData)
}

