// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface ArtistExternalLinksOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated string websiteUrl = 1;
  /**
   * <code>repeated string websiteUrl = 1;</code>
   */
  java.util.List<java.lang.String>
  getWebsiteUrlList();
  /**
   * <code>repeated string websiteUrl = 1;</code>
   */
  int getWebsiteUrlCount();
  /**
   * <code>repeated string websiteUrl = 1;</code>
   */
  java.lang.String getWebsiteUrl(int index);
  /**
   * <code>repeated string websiteUrl = 1;</code>
   */
  com.google.protobuf.ByteString
      getWebsiteUrlBytes(int index);

  // optional string googlePlusProfileUrl = 2;
  /**
   * <code>optional string googlePlusProfileUrl = 2;</code>
   */
  boolean hasGooglePlusProfileUrl();
  /**
   * <code>optional string googlePlusProfileUrl = 2;</code>
   */
  java.lang.String getGooglePlusProfileUrl();
  /**
   * <code>optional string googlePlusProfileUrl = 2;</code>
   */
  com.google.protobuf.ByteString
      getGooglePlusProfileUrlBytes();

  // optional string youtubeChannelUrl = 3;
  /**
   * <code>optional string youtubeChannelUrl = 3;</code>
   */
  boolean hasYoutubeChannelUrl();
  /**
   * <code>optional string youtubeChannelUrl = 3;</code>
   */
  java.lang.String getYoutubeChannelUrl();
  /**
   * <code>optional string youtubeChannelUrl = 3;</code>
   */
  com.google.protobuf.ByteString
      getYoutubeChannelUrlBytes();
}
