// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface AuthenticationChallengeOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 authenticationType = 1;
  /**
   * <code>optional int32 authenticationType = 1;</code>
   */
  boolean hasAuthenticationType();
  /**
   * <code>optional int32 authenticationType = 1;</code>
   */
  int getAuthenticationType();

  // optional string responseAuthenticationTypeParam = 2;
  /**
   * <code>optional string responseAuthenticationTypeParam = 2;</code>
   */
  boolean hasResponseAuthenticationTypeParam();
  /**
   * <code>optional string responseAuthenticationTypeParam = 2;</code>
   */
  java.lang.String getResponseAuthenticationTypeParam();
  /**
   * <code>optional string responseAuthenticationTypeParam = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseAuthenticationTypeParamBytes();

  // optional string responseRetryCountParam = 3;
  /**
   * <code>optional string responseRetryCountParam = 3;</code>
   */
  boolean hasResponseRetryCountParam();
  /**
   * <code>optional string responseRetryCountParam = 3;</code>
   */
  java.lang.String getResponseRetryCountParam();
  /**
   * <code>optional string responseRetryCountParam = 3;</code>
   */
  com.google.protobuf.ByteString
      getResponseRetryCountParamBytes();

  // optional string pinHeaderText = 4;
  /**
   * <code>optional string pinHeaderText = 4;</code>
   */
  boolean hasPinHeaderText();
  /**
   * <code>optional string pinHeaderText = 4;</code>
   */
  java.lang.String getPinHeaderText();
  /**
   * <code>optional string pinHeaderText = 4;</code>
   */
  com.google.protobuf.ByteString
      getPinHeaderTextBytes();

  // optional string pinDescriptionTextHtml = 5;
  /**
   * <code>optional string pinDescriptionTextHtml = 5;</code>
   */
  boolean hasPinDescriptionTextHtml();
  /**
   * <code>optional string pinDescriptionTextHtml = 5;</code>
   */
  java.lang.String getPinDescriptionTextHtml();
  /**
   * <code>optional string pinDescriptionTextHtml = 5;</code>
   */
  com.google.protobuf.ByteString
      getPinDescriptionTextHtmlBytes();

  // optional string gaiaHeaderText = 6;
  /**
   * <code>optional string gaiaHeaderText = 6;</code>
   */
  boolean hasGaiaHeaderText();
  /**
   * <code>optional string gaiaHeaderText = 6;</code>
   */
  java.lang.String getGaiaHeaderText();
  /**
   * <code>optional string gaiaHeaderText = 6;</code>
   */
  com.google.protobuf.ByteString
      getGaiaHeaderTextBytes();

  // optional string gaiaDescriptionTextHtml = 7;
  /**
   * <code>optional string gaiaDescriptionTextHtml = 7;</code>
   */
  boolean hasGaiaDescriptionTextHtml();
  /**
   * <code>optional string gaiaDescriptionTextHtml = 7;</code>
   */
  java.lang.String getGaiaDescriptionTextHtml();
  /**
   * <code>optional string gaiaDescriptionTextHtml = 7;</code>
   */
  com.google.protobuf.ByteString
      getGaiaDescriptionTextHtmlBytes();
}
