// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface BillingAddressSpecOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 billingAddressType = 1;
  /**
   * <code>optional int32 billingAddressType = 1;</code>
   */
  boolean hasBillingAddressType();
  /**
   * <code>optional int32 billingAddressType = 1;</code>
   */
  int getBillingAddressType();

  // repeated int32 requiredField = 2;
  /**
   * <code>repeated int32 requiredField = 2;</code>
   */
  java.util.List<java.lang.Integer> getRequiredFieldList();
  /**
   * <code>repeated int32 requiredField = 2;</code>
   */
  int getRequiredFieldCount();
  /**
   * <code>repeated int32 requiredField = 2;</code>
   */
  int getRequiredField(int index);
}
