// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface BookSubjectOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string name = 1;
  /**
   * <code>optional string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // optional string query = 2;
  /**
   * <code>optional string query = 2;</code>
   */
  boolean hasQuery();
  /**
   * <code>optional string query = 2;</code>
   */
  java.lang.String getQuery();
  /**
   * <code>optional string query = 2;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  // optional string subjectId = 3;
  /**
   * <code>optional string subjectId = 3;</code>
   */
  boolean hasSubjectId();
  /**
   * <code>optional string subjectId = 3;</code>
   */
  java.lang.String getSubjectId();
  /**
   * <code>optional string subjectId = 3;</code>
   */
  com.google.protobuf.ByteString
      getSubjectIdBytes();
}
