// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface CategoryInfoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string appType = 1;
  /**
   * <code>optional string appType = 1;</code>
   */
  boolean hasAppType();
  /**
   * <code>optional string appType = 1;</code>
   */
  java.lang.String getAppType();
  /**
   * <code>optional string appType = 1;</code>
   */
  com.google.protobuf.ByteString
      getAppTypeBytes();

  // optional string appCategory = 2;
  /**
   * <code>optional string appCategory = 2;</code>
   */
  boolean hasAppCategory();
  /**
   * <code>optional string appCategory = 2;</code>
   */
  java.lang.String getAppCategory();
  /**
   * <code>optional string appCategory = 2;</code>
   */
  com.google.protobuf.ByteString
      getAppCategoryBytes();
}
