// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface ClientLibraryStateOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 corpus = 1;
  /**
   * <code>optional int32 corpus = 1;</code>
   */
  boolean hasCorpus();
  /**
   * <code>optional int32 corpus = 1;</code>
   */
  int getCorpus();

  // optional bytes serverToken = 2;
  /**
   * <code>optional bytes serverToken = 2;</code>
   */
  boolean hasServerToken();
  /**
   * <code>optional bytes serverToken = 2;</code>
   */
  com.google.protobuf.ByteString getServerToken();

  // optional int64 hashCodeSum = 3;
  /**
   * <code>optional int64 hashCodeSum = 3;</code>
   */
  boolean hasHashCodeSum();
  /**
   * <code>optional int64 hashCodeSum = 3;</code>
   */
  long getHashCodeSum();

  // optional int32 librarySize = 4;
  /**
   * <code>optional int32 librarySize = 4;</code>
   */
  boolean hasLibrarySize();
  /**
   * <code>optional int32 librarySize = 4;</code>
   */
  int getLibrarySize();

  // optional string libraryId = 5;
  /**
   * <code>optional string libraryId = 5;</code>
   */
  boolean hasLibraryId();
  /**
   * <code>optional string libraryId = 5;</code>
   */
  java.lang.String getLibraryId();
  /**
   * <code>optional string libraryId = 5;</code>
   */
  com.google.protobuf.ByteString
      getLibraryIdBytes();
}
