// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface ContainerMetadataOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string browseUrl = 1;
  /**
   * <code>optional string browseUrl = 1;</code>
   */
  boolean hasBrowseUrl();
  /**
   * <code>optional string browseUrl = 1;</code>
   */
  java.lang.String getBrowseUrl();
  /**
   * <code>optional string browseUrl = 1;</code>
   */
  com.google.protobuf.ByteString
      getBrowseUrlBytes();

  // optional string nextPageUrl = 2;
  /**
   * <code>optional string nextPageUrl = 2;</code>
   */
  boolean hasNextPageUrl();
  /**
   * <code>optional string nextPageUrl = 2;</code>
   */
  java.lang.String getNextPageUrl();
  /**
   * <code>optional string nextPageUrl = 2;</code>
   */
  com.google.protobuf.ByteString
      getNextPageUrlBytes();

  // optional double relevance = 3;
  /**
   * <code>optional double relevance = 3;</code>
   */
  boolean hasRelevance();
  /**
   * <code>optional double relevance = 3;</code>
   */
  double getRelevance();

  // optional int64 estimatedResults = 4;
  /**
   * <code>optional int64 estimatedResults = 4;</code>
   */
  boolean hasEstimatedResults();
  /**
   * <code>optional int64 estimatedResults = 4;</code>
   */
  long getEstimatedResults();

  // optional string analyticsCookie = 5;
  /**
   * <code>optional string analyticsCookie = 5;</code>
   */
  boolean hasAnalyticsCookie();
  /**
   * <code>optional string analyticsCookie = 5;</code>
   */
  java.lang.String getAnalyticsCookie();
  /**
   * <code>optional string analyticsCookie = 5;</code>
   */
  com.google.protobuf.ByteString
      getAnalyticsCookieBytes();

  // optional bool ordered = 6;
  /**
   * <code>optional bool ordered = 6;</code>
   */
  boolean hasOrdered();
  /**
   * <code>optional bool ordered = 6;</code>
   */
  boolean getOrdered();
}
