// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface DeliveryResponseOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .AndroidAppDeliveryData appDeliveryData = 2;
  /**
   * <code>optional .AndroidAppDeliveryData appDeliveryData = 2;</code>
   */
  boolean hasAppDeliveryData();
  /**
   * <code>optional .AndroidAppDeliveryData appDeliveryData = 2;</code>
   */
  com.github.yeriomin.playstoreapi.AndroidAppDeliveryData getAppDeliveryData();
  /**
   * <code>optional .AndroidAppDeliveryData appDeliveryData = 2;</code>
   */
  com.github.yeriomin.playstoreapi.AndroidAppDeliveryDataOrBuilder getAppDeliveryDataOrBuilder();
}
