// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface EncryptedSubscriberInfoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string data = 1;
  /**
   * <code>optional string data = 1;</code>
   */
  boolean hasData();
  /**
   * <code>optional string data = 1;</code>
   */
  java.lang.String getData();
  /**
   * <code>optional string data = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();

  // optional string encryptedKey = 2;
  /**
   * <code>optional string encryptedKey = 2;</code>
   */
  boolean hasEncryptedKey();
  /**
   * <code>optional string encryptedKey = 2;</code>
   */
  java.lang.String getEncryptedKey();
  /**
   * <code>optional string encryptedKey = 2;</code>
   */
  com.google.protobuf.ByteString
      getEncryptedKeyBytes();

  // optional string signature = 3;
  /**
   * <code>optional string signature = 3;</code>
   */
  boolean hasSignature();
  /**
   * <code>optional string signature = 3;</code>
   */
  java.lang.String getSignature();
  /**
   * <code>optional string signature = 3;</code>
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  // optional string initVector = 4;
  /**
   * <code>optional string initVector = 4;</code>
   */
  boolean hasInitVector();
  /**
   * <code>optional string initVector = 4;</code>
   */
  java.lang.String getInitVector();
  /**
   * <code>optional string initVector = 4;</code>
   */
  com.google.protobuf.ByteString
      getInitVectorBytes();

  // optional int32 googleKeyVersion = 5;
  /**
   * <code>optional int32 googleKeyVersion = 5;</code>
   */
  boolean hasGoogleKeyVersion();
  /**
   * <code>optional int32 googleKeyVersion = 5;</code>
   */
  int getGoogleKeyVersion();

  // optional int32 carrierKeyVersion = 6;
  /**
   * <code>optional int32 carrierKeyVersion = 6;</code>
   */
  boolean hasCarrierKeyVersion();
  /**
   * <code>optional int32 carrierKeyVersion = 6;</code>
   */
  int getCarrierKeyVersion();
}
