// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface InstrumentOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string instrumentId = 1;
  /**
   * <code>optional string instrumentId = 1;</code>
   */
  boolean hasInstrumentId();
  /**
   * <code>optional string instrumentId = 1;</code>
   */
  java.lang.String getInstrumentId();
  /**
   * <code>optional string instrumentId = 1;</code>
   */
  com.google.protobuf.ByteString
      getInstrumentIdBytes();

  // optional .Address billingAddress = 2;
  /**
   * <code>optional .Address billingAddress = 2;</code>
   */
  boolean hasBillingAddress();
  /**
   * <code>optional .Address billingAddress = 2;</code>
   */
  com.github.yeriomin.playstoreapi.Address getBillingAddress();
  /**
   * <code>optional .Address billingAddress = 2;</code>
   */
  com.github.yeriomin.playstoreapi.AddressOrBuilder getBillingAddressOrBuilder();

  // optional .CreditCardInstrument creditCard = 3;
  /**
   * <code>optional .CreditCardInstrument creditCard = 3;</code>
   */
  boolean hasCreditCard();
  /**
   * <code>optional .CreditCardInstrument creditCard = 3;</code>
   */
  com.github.yeriomin.playstoreapi.CreditCardInstrument getCreditCard();
  /**
   * <code>optional .CreditCardInstrument creditCard = 3;</code>
   */
  com.github.yeriomin.playstoreapi.CreditCardInstrumentOrBuilder getCreditCardOrBuilder();

  // optional .CarrierBillingInstrument carrierBilling = 4;
  /**
   * <code>optional .CarrierBillingInstrument carrierBilling = 4;</code>
   */
  boolean hasCarrierBilling();
  /**
   * <code>optional .CarrierBillingInstrument carrierBilling = 4;</code>
   */
  com.github.yeriomin.playstoreapi.CarrierBillingInstrument getCarrierBilling();
  /**
   * <code>optional .CarrierBillingInstrument carrierBilling = 4;</code>
   */
  com.github.yeriomin.playstoreapi.CarrierBillingInstrumentOrBuilder getCarrierBillingOrBuilder();

  // optional .BillingAddressSpec billingAddressSpec = 5;
  /**
   * <code>optional .BillingAddressSpec billingAddressSpec = 5;</code>
   */
  boolean hasBillingAddressSpec();
  /**
   * <code>optional .BillingAddressSpec billingAddressSpec = 5;</code>
   */
  com.github.yeriomin.playstoreapi.BillingAddressSpec getBillingAddressSpec();
  /**
   * <code>optional .BillingAddressSpec billingAddressSpec = 5;</code>
   */
  com.github.yeriomin.playstoreapi.BillingAddressSpecOrBuilder getBillingAddressSpecOrBuilder();

  // optional int32 instrumentFamily = 6;
  /**
   * <code>optional int32 instrumentFamily = 6;</code>
   */
  boolean hasInstrumentFamily();
  /**
   * <code>optional int32 instrumentFamily = 6;</code>
   */
  int getInstrumentFamily();

  // optional .CarrierBillingInstrumentStatus carrierBillingStatus = 7;
  /**
   * <code>optional .CarrierBillingInstrumentStatus carrierBillingStatus = 7;</code>
   */
  boolean hasCarrierBillingStatus();
  /**
   * <code>optional .CarrierBillingInstrumentStatus carrierBillingStatus = 7;</code>
   */
  com.github.yeriomin.playstoreapi.CarrierBillingInstrumentStatus getCarrierBillingStatus();
  /**
   * <code>optional .CarrierBillingInstrumentStatus carrierBillingStatus = 7;</code>
   */
  com.github.yeriomin.playstoreapi.CarrierBillingInstrumentStatusOrBuilder getCarrierBillingStatusOrBuilder();

  // optional string displayTitle = 8;
  /**
   * <code>optional string displayTitle = 8;</code>
   */
  boolean hasDisplayTitle();
  /**
   * <code>optional string displayTitle = 8;</code>
   */
  java.lang.String getDisplayTitle();
  /**
   * <code>optional string displayTitle = 8;</code>
   */
  com.google.protobuf.ByteString
      getDisplayTitleBytes();
}
