// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

/**
 * Protobuf type {@code LibraryMutation}
 */
public  final class LibraryMutation extends
    com.google.protobuf.GeneratedMessage
    implements LibraryMutationOrBuilder {
  // Use LibraryMutation.newBuilder() to construct.
  private LibraryMutation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private LibraryMutation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final LibraryMutation defaultInstance;
  public static LibraryMutation getDefaultInstance() {
    return defaultInstance;
  }

  public LibraryMutation getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private LibraryMutation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.github.yeriomin.playstoreapi.Docid.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = docid_.toBuilder();
            }
            docid_ = input.readMessage(com.github.yeriomin.playstoreapi.Docid.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(docid_);
              docid_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            offerType_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            documentHash_ = input.readInt64();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            deleted_ = input.readBool();
            break;
          }
          case 42: {
            com.github.yeriomin.playstoreapi.LibraryAppDetails.Builder subBuilder = null;
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
              subBuilder = appDetails_.toBuilder();
            }
            appDetails_ = input.readMessage(com.github.yeriomin.playstoreapi.LibraryAppDetails.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(appDetails_);
              appDetails_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000010;
            break;
          }
          case 50: {
            com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.Builder subBuilder = null;
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
              subBuilder = subscriptionDetails_.toBuilder();
            }
            subscriptionDetails_ = input.readMessage(com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(subscriptionDetails_);
              subscriptionDetails_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000020;
            break;
          }
          case 58: {
            com.github.yeriomin.playstoreapi.LibraryInAppDetails.Builder subBuilder = null;
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
              subBuilder = inAppDetails_.toBuilder();
            }
            inAppDetails_ = input.readMessage(com.github.yeriomin.playstoreapi.LibraryInAppDetails.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(inAppDetails_);
              inAppDetails_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000040;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_LibraryMutation_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_LibraryMutation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.yeriomin.playstoreapi.LibraryMutation.class, com.github.yeriomin.playstoreapi.LibraryMutation.Builder.class);
  }

  public static com.google.protobuf.Parser<LibraryMutation> PARSER =
      new com.google.protobuf.AbstractParser<LibraryMutation>() {
    public LibraryMutation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LibraryMutation(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<LibraryMutation> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional .Docid docid = 1;
  public static final int DOCID_FIELD_NUMBER = 1;
  private com.github.yeriomin.playstoreapi.Docid docid_;
  /**
   * <code>optional .Docid docid = 1;</code>
   */
  public boolean hasDocid() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .Docid docid = 1;</code>
   */
  public com.github.yeriomin.playstoreapi.Docid getDocid() {
    return docid_;
  }
  /**
   * <code>optional .Docid docid = 1;</code>
   */
  public com.github.yeriomin.playstoreapi.DocidOrBuilder getDocidOrBuilder() {
    return docid_;
  }

  // optional int32 offerType = 2;
  public static final int OFFERTYPE_FIELD_NUMBER = 2;
  private int offerType_;
  /**
   * <code>optional int32 offerType = 2;</code>
   */
  public boolean hasOfferType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 offerType = 2;</code>
   */
  public int getOfferType() {
    return offerType_;
  }

  // optional int64 documentHash = 3;
  public static final int DOCUMENTHASH_FIELD_NUMBER = 3;
  private long documentHash_;
  /**
   * <code>optional int64 documentHash = 3;</code>
   */
  public boolean hasDocumentHash() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int64 documentHash = 3;</code>
   */
  public long getDocumentHash() {
    return documentHash_;
  }

  // optional bool deleted = 4;
  public static final int DELETED_FIELD_NUMBER = 4;
  private boolean deleted_;
  /**
   * <code>optional bool deleted = 4;</code>
   */
  public boolean hasDeleted() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional bool deleted = 4;</code>
   */
  public boolean getDeleted() {
    return deleted_;
  }

  // optional .LibraryAppDetails appDetails = 5;
  public static final int APPDETAILS_FIELD_NUMBER = 5;
  private com.github.yeriomin.playstoreapi.LibraryAppDetails appDetails_;
  /**
   * <code>optional .LibraryAppDetails appDetails = 5;</code>
   */
  public boolean hasAppDetails() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional .LibraryAppDetails appDetails = 5;</code>
   */
  public com.github.yeriomin.playstoreapi.LibraryAppDetails getAppDetails() {
    return appDetails_;
  }
  /**
   * <code>optional .LibraryAppDetails appDetails = 5;</code>
   */
  public com.github.yeriomin.playstoreapi.LibraryAppDetailsOrBuilder getAppDetailsOrBuilder() {
    return appDetails_;
  }

  // optional .LibrarySubscriptionDetails subscriptionDetails = 6;
  public static final int SUBSCRIPTIONDETAILS_FIELD_NUMBER = 6;
  private com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails subscriptionDetails_;
  /**
   * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
   */
  public boolean hasSubscriptionDetails() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
   */
  public com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails getSubscriptionDetails() {
    return subscriptionDetails_;
  }
  /**
   * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
   */
  public com.github.yeriomin.playstoreapi.LibrarySubscriptionDetailsOrBuilder getSubscriptionDetailsOrBuilder() {
    return subscriptionDetails_;
  }

  // optional .LibraryInAppDetails inAppDetails = 7;
  public static final int INAPPDETAILS_FIELD_NUMBER = 7;
  private com.github.yeriomin.playstoreapi.LibraryInAppDetails inAppDetails_;
  /**
   * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
   */
  public boolean hasInAppDetails() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
   */
  public com.github.yeriomin.playstoreapi.LibraryInAppDetails getInAppDetails() {
    return inAppDetails_;
  }
  /**
   * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
   */
  public com.github.yeriomin.playstoreapi.LibraryInAppDetailsOrBuilder getInAppDetailsOrBuilder() {
    return inAppDetails_;
  }

  private void initFields() {
    docid_ = com.github.yeriomin.playstoreapi.Docid.getDefaultInstance();
    offerType_ = 0;
    documentHash_ = 0L;
    deleted_ = false;
    appDetails_ = com.github.yeriomin.playstoreapi.LibraryAppDetails.getDefaultInstance();
    subscriptionDetails_ = com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.getDefaultInstance();
    inAppDetails_ = com.github.yeriomin.playstoreapi.LibraryInAppDetails.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, docid_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, offerType_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, documentHash_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBool(4, deleted_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeMessage(5, appDetails_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeMessage(6, subscriptionDetails_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeMessage(7, inAppDetails_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, docid_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, offerType_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, documentHash_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, deleted_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, appDetails_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, subscriptionDetails_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, inAppDetails_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.github.yeriomin.playstoreapi.LibraryMutation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.yeriomin.playstoreapi.LibraryMutation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.LibraryMutation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.yeriomin.playstoreapi.LibraryMutation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.LibraryMutation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.LibraryMutation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.LibraryMutation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.LibraryMutation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.LibraryMutation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.LibraryMutation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.github.yeriomin.playstoreapi.LibraryMutation prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LibraryMutation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.github.yeriomin.playstoreapi.LibraryMutationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_LibraryMutation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_LibraryMutation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.yeriomin.playstoreapi.LibraryMutation.class, com.github.yeriomin.playstoreapi.LibraryMutation.Builder.class);
    }

    // Construct using com.github.yeriomin.playstoreapi.LibraryMutation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getDocidFieldBuilder();
        getAppDetailsFieldBuilder();
        getSubscriptionDetailsFieldBuilder();
        getInAppDetailsFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (docidBuilder_ == null) {
        docid_ = com.github.yeriomin.playstoreapi.Docid.getDefaultInstance();
      } else {
        docidBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      offerType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      documentHash_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      deleted_ = false;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (appDetailsBuilder_ == null) {
        appDetails_ = com.github.yeriomin.playstoreapi.LibraryAppDetails.getDefaultInstance();
      } else {
        appDetailsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (subscriptionDetailsBuilder_ == null) {
        subscriptionDetails_ = com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.getDefaultInstance();
      } else {
        subscriptionDetailsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (inAppDetailsBuilder_ == null) {
        inAppDetails_ = com.github.yeriomin.playstoreapi.LibraryInAppDetails.getDefaultInstance();
      } else {
        inAppDetailsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_LibraryMutation_descriptor;
    }

    public com.github.yeriomin.playstoreapi.LibraryMutation getDefaultInstanceForType() {
      return com.github.yeriomin.playstoreapi.LibraryMutation.getDefaultInstance();
    }

    public com.github.yeriomin.playstoreapi.LibraryMutation build() {
      com.github.yeriomin.playstoreapi.LibraryMutation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.yeriomin.playstoreapi.LibraryMutation buildPartial() {
      com.github.yeriomin.playstoreapi.LibraryMutation result = new com.github.yeriomin.playstoreapi.LibraryMutation(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (docidBuilder_ == null) {
        result.docid_ = docid_;
      } else {
        result.docid_ = docidBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.offerType_ = offerType_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.documentHash_ = documentHash_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.deleted_ = deleted_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      if (appDetailsBuilder_ == null) {
        result.appDetails_ = appDetails_;
      } else {
        result.appDetails_ = appDetailsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      if (subscriptionDetailsBuilder_ == null) {
        result.subscriptionDetails_ = subscriptionDetails_;
      } else {
        result.subscriptionDetails_ = subscriptionDetailsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      if (inAppDetailsBuilder_ == null) {
        result.inAppDetails_ = inAppDetails_;
      } else {
        result.inAppDetails_ = inAppDetailsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.yeriomin.playstoreapi.LibraryMutation) {
        return mergeFrom((com.github.yeriomin.playstoreapi.LibraryMutation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.yeriomin.playstoreapi.LibraryMutation other) {
      if (other == com.github.yeriomin.playstoreapi.LibraryMutation.getDefaultInstance()) return this;
      if (other.hasDocid()) {
        mergeDocid(other.getDocid());
      }
      if (other.hasOfferType()) {
        setOfferType(other.getOfferType());
      }
      if (other.hasDocumentHash()) {
        setDocumentHash(other.getDocumentHash());
      }
      if (other.hasDeleted()) {
        setDeleted(other.getDeleted());
      }
      if (other.hasAppDetails()) {
        mergeAppDetails(other.getAppDetails());
      }
      if (other.hasSubscriptionDetails()) {
        mergeSubscriptionDetails(other.getSubscriptionDetails());
      }
      if (other.hasInAppDetails()) {
        mergeInAppDetails(other.getInAppDetails());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.yeriomin.playstoreapi.LibraryMutation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.yeriomin.playstoreapi.LibraryMutation) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional .Docid docid = 1;
    private com.github.yeriomin.playstoreapi.Docid docid_ = com.github.yeriomin.playstoreapi.Docid.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.Docid, com.github.yeriomin.playstoreapi.Docid.Builder, com.github.yeriomin.playstoreapi.DocidOrBuilder> docidBuilder_;
    /**
     * <code>optional .Docid docid = 1;</code>
     */
    public boolean hasDocid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Docid docid = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.Docid getDocid() {
      if (docidBuilder_ == null) {
        return docid_;
      } else {
        return docidBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Docid docid = 1;</code>
     */
    public Builder setDocid(com.github.yeriomin.playstoreapi.Docid value) {
      if (docidBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        docid_ = value;
        onChanged();
      } else {
        docidBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .Docid docid = 1;</code>
     */
    public Builder setDocid(
        com.github.yeriomin.playstoreapi.Docid.Builder builderForValue) {
      if (docidBuilder_ == null) {
        docid_ = builderForValue.build();
        onChanged();
      } else {
        docidBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .Docid docid = 1;</code>
     */
    public Builder mergeDocid(com.github.yeriomin.playstoreapi.Docid value) {
      if (docidBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            docid_ != com.github.yeriomin.playstoreapi.Docid.getDefaultInstance()) {
          docid_ =
            com.github.yeriomin.playstoreapi.Docid.newBuilder(docid_).mergeFrom(value).buildPartial();
        } else {
          docid_ = value;
        }
        onChanged();
      } else {
        docidBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .Docid docid = 1;</code>
     */
    public Builder clearDocid() {
      if (docidBuilder_ == null) {
        docid_ = com.github.yeriomin.playstoreapi.Docid.getDefaultInstance();
        onChanged();
      } else {
        docidBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .Docid docid = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.Docid.Builder getDocidBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDocidFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Docid docid = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.DocidOrBuilder getDocidOrBuilder() {
      if (docidBuilder_ != null) {
        return docidBuilder_.getMessageOrBuilder();
      } else {
        return docid_;
      }
    }
    /**
     * <code>optional .Docid docid = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.Docid, com.github.yeriomin.playstoreapi.Docid.Builder, com.github.yeriomin.playstoreapi.DocidOrBuilder> 
        getDocidFieldBuilder() {
      if (docidBuilder_ == null) {
        docidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.Docid, com.github.yeriomin.playstoreapi.Docid.Builder, com.github.yeriomin.playstoreapi.DocidOrBuilder>(
                docid_,
                getParentForChildren(),
                isClean());
        docid_ = null;
      }
      return docidBuilder_;
    }

    // optional int32 offerType = 2;
    private int offerType_ ;
    /**
     * <code>optional int32 offerType = 2;</code>
     */
    public boolean hasOfferType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 offerType = 2;</code>
     */
    public int getOfferType() {
      return offerType_;
    }
    /**
     * <code>optional int32 offerType = 2;</code>
     */
    public Builder setOfferType(int value) {
      bitField0_ |= 0x00000002;
      offerType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 offerType = 2;</code>
     */
    public Builder clearOfferType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      offerType_ = 0;
      onChanged();
      return this;
    }

    // optional int64 documentHash = 3;
    private long documentHash_ ;
    /**
     * <code>optional int64 documentHash = 3;</code>
     */
    public boolean hasDocumentHash() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 documentHash = 3;</code>
     */
    public long getDocumentHash() {
      return documentHash_;
    }
    /**
     * <code>optional int64 documentHash = 3;</code>
     */
    public Builder setDocumentHash(long value) {
      bitField0_ |= 0x00000004;
      documentHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 documentHash = 3;</code>
     */
    public Builder clearDocumentHash() {
      bitField0_ = (bitField0_ & ~0x00000004);
      documentHash_ = 0L;
      onChanged();
      return this;
    }

    // optional bool deleted = 4;
    private boolean deleted_ ;
    /**
     * <code>optional bool deleted = 4;</code>
     */
    public boolean hasDeleted() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool deleted = 4;</code>
     */
    public boolean getDeleted() {
      return deleted_;
    }
    /**
     * <code>optional bool deleted = 4;</code>
     */
    public Builder setDeleted(boolean value) {
      bitField0_ |= 0x00000008;
      deleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool deleted = 4;</code>
     */
    public Builder clearDeleted() {
      bitField0_ = (bitField0_ & ~0x00000008);
      deleted_ = false;
      onChanged();
      return this;
    }

    // optional .LibraryAppDetails appDetails = 5;
    private com.github.yeriomin.playstoreapi.LibraryAppDetails appDetails_ = com.github.yeriomin.playstoreapi.LibraryAppDetails.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.LibraryAppDetails, com.github.yeriomin.playstoreapi.LibraryAppDetails.Builder, com.github.yeriomin.playstoreapi.LibraryAppDetailsOrBuilder> appDetailsBuilder_;
    /**
     * <code>optional .LibraryAppDetails appDetails = 5;</code>
     */
    public boolean hasAppDetails() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .LibraryAppDetails appDetails = 5;</code>
     */
    public com.github.yeriomin.playstoreapi.LibraryAppDetails getAppDetails() {
      if (appDetailsBuilder_ == null) {
        return appDetails_;
      } else {
        return appDetailsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .LibraryAppDetails appDetails = 5;</code>
     */
    public Builder setAppDetails(com.github.yeriomin.playstoreapi.LibraryAppDetails value) {
      if (appDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        appDetails_ = value;
        onChanged();
      } else {
        appDetailsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .LibraryAppDetails appDetails = 5;</code>
     */
    public Builder setAppDetails(
        com.github.yeriomin.playstoreapi.LibraryAppDetails.Builder builderForValue) {
      if (appDetailsBuilder_ == null) {
        appDetails_ = builderForValue.build();
        onChanged();
      } else {
        appDetailsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .LibraryAppDetails appDetails = 5;</code>
     */
    public Builder mergeAppDetails(com.github.yeriomin.playstoreapi.LibraryAppDetails value) {
      if (appDetailsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010) &&
            appDetails_ != com.github.yeriomin.playstoreapi.LibraryAppDetails.getDefaultInstance()) {
          appDetails_ =
            com.github.yeriomin.playstoreapi.LibraryAppDetails.newBuilder(appDetails_).mergeFrom(value).buildPartial();
        } else {
          appDetails_ = value;
        }
        onChanged();
      } else {
        appDetailsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .LibraryAppDetails appDetails = 5;</code>
     */
    public Builder clearAppDetails() {
      if (appDetailsBuilder_ == null) {
        appDetails_ = com.github.yeriomin.playstoreapi.LibraryAppDetails.getDefaultInstance();
        onChanged();
      } else {
        appDetailsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <code>optional .LibraryAppDetails appDetails = 5;</code>
     */
    public com.github.yeriomin.playstoreapi.LibraryAppDetails.Builder getAppDetailsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getAppDetailsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .LibraryAppDetails appDetails = 5;</code>
     */
    public com.github.yeriomin.playstoreapi.LibraryAppDetailsOrBuilder getAppDetailsOrBuilder() {
      if (appDetailsBuilder_ != null) {
        return appDetailsBuilder_.getMessageOrBuilder();
      } else {
        return appDetails_;
      }
    }
    /**
     * <code>optional .LibraryAppDetails appDetails = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.LibraryAppDetails, com.github.yeriomin.playstoreapi.LibraryAppDetails.Builder, com.github.yeriomin.playstoreapi.LibraryAppDetailsOrBuilder> 
        getAppDetailsFieldBuilder() {
      if (appDetailsBuilder_ == null) {
        appDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.LibraryAppDetails, com.github.yeriomin.playstoreapi.LibraryAppDetails.Builder, com.github.yeriomin.playstoreapi.LibraryAppDetailsOrBuilder>(
                appDetails_,
                getParentForChildren(),
                isClean());
        appDetails_ = null;
      }
      return appDetailsBuilder_;
    }

    // optional .LibrarySubscriptionDetails subscriptionDetails = 6;
    private com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails subscriptionDetails_ = com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails, com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.Builder, com.github.yeriomin.playstoreapi.LibrarySubscriptionDetailsOrBuilder> subscriptionDetailsBuilder_;
    /**
     * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
     */
    public boolean hasSubscriptionDetails() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
     */
    public com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails getSubscriptionDetails() {
      if (subscriptionDetailsBuilder_ == null) {
        return subscriptionDetails_;
      } else {
        return subscriptionDetailsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
     */
    public Builder setSubscriptionDetails(com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails value) {
      if (subscriptionDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        subscriptionDetails_ = value;
        onChanged();
      } else {
        subscriptionDetailsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
     */
    public Builder setSubscriptionDetails(
        com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.Builder builderForValue) {
      if (subscriptionDetailsBuilder_ == null) {
        subscriptionDetails_ = builderForValue.build();
        onChanged();
      } else {
        subscriptionDetailsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
     */
    public Builder mergeSubscriptionDetails(com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails value) {
      if (subscriptionDetailsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020) &&
            subscriptionDetails_ != com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.getDefaultInstance()) {
          subscriptionDetails_ =
            com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.newBuilder(subscriptionDetails_).mergeFrom(value).buildPartial();
        } else {
          subscriptionDetails_ = value;
        }
        onChanged();
      } else {
        subscriptionDetailsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
     */
    public Builder clearSubscriptionDetails() {
      if (subscriptionDetailsBuilder_ == null) {
        subscriptionDetails_ = com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.getDefaultInstance();
        onChanged();
      } else {
        subscriptionDetailsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }
    /**
     * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
     */
    public com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.Builder getSubscriptionDetailsBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getSubscriptionDetailsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
     */
    public com.github.yeriomin.playstoreapi.LibrarySubscriptionDetailsOrBuilder getSubscriptionDetailsOrBuilder() {
      if (subscriptionDetailsBuilder_ != null) {
        return subscriptionDetailsBuilder_.getMessageOrBuilder();
      } else {
        return subscriptionDetails_;
      }
    }
    /**
     * <code>optional .LibrarySubscriptionDetails subscriptionDetails = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails, com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.Builder, com.github.yeriomin.playstoreapi.LibrarySubscriptionDetailsOrBuilder> 
        getSubscriptionDetailsFieldBuilder() {
      if (subscriptionDetailsBuilder_ == null) {
        subscriptionDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails, com.github.yeriomin.playstoreapi.LibrarySubscriptionDetails.Builder, com.github.yeriomin.playstoreapi.LibrarySubscriptionDetailsOrBuilder>(
                subscriptionDetails_,
                getParentForChildren(),
                isClean());
        subscriptionDetails_ = null;
      }
      return subscriptionDetailsBuilder_;
    }

    // optional .LibraryInAppDetails inAppDetails = 7;
    private com.github.yeriomin.playstoreapi.LibraryInAppDetails inAppDetails_ = com.github.yeriomin.playstoreapi.LibraryInAppDetails.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.LibraryInAppDetails, com.github.yeriomin.playstoreapi.LibraryInAppDetails.Builder, com.github.yeriomin.playstoreapi.LibraryInAppDetailsOrBuilder> inAppDetailsBuilder_;
    /**
     * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
     */
    public boolean hasInAppDetails() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
     */
    public com.github.yeriomin.playstoreapi.LibraryInAppDetails getInAppDetails() {
      if (inAppDetailsBuilder_ == null) {
        return inAppDetails_;
      } else {
        return inAppDetailsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
     */
    public Builder setInAppDetails(com.github.yeriomin.playstoreapi.LibraryInAppDetails value) {
      if (inAppDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inAppDetails_ = value;
        onChanged();
      } else {
        inAppDetailsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
     */
    public Builder setInAppDetails(
        com.github.yeriomin.playstoreapi.LibraryInAppDetails.Builder builderForValue) {
      if (inAppDetailsBuilder_ == null) {
        inAppDetails_ = builderForValue.build();
        onChanged();
      } else {
        inAppDetailsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
     */
    public Builder mergeInAppDetails(com.github.yeriomin.playstoreapi.LibraryInAppDetails value) {
      if (inAppDetailsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040) &&
            inAppDetails_ != com.github.yeriomin.playstoreapi.LibraryInAppDetails.getDefaultInstance()) {
          inAppDetails_ =
            com.github.yeriomin.playstoreapi.LibraryInAppDetails.newBuilder(inAppDetails_).mergeFrom(value).buildPartial();
        } else {
          inAppDetails_ = value;
        }
        onChanged();
      } else {
        inAppDetailsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
     */
    public Builder clearInAppDetails() {
      if (inAppDetailsBuilder_ == null) {
        inAppDetails_ = com.github.yeriomin.playstoreapi.LibraryInAppDetails.getDefaultInstance();
        onChanged();
      } else {
        inAppDetailsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }
    /**
     * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
     */
    public com.github.yeriomin.playstoreapi.LibraryInAppDetails.Builder getInAppDetailsBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getInAppDetailsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
     */
    public com.github.yeriomin.playstoreapi.LibraryInAppDetailsOrBuilder getInAppDetailsOrBuilder() {
      if (inAppDetailsBuilder_ != null) {
        return inAppDetailsBuilder_.getMessageOrBuilder();
      } else {
        return inAppDetails_;
      }
    }
    /**
     * <code>optional .LibraryInAppDetails inAppDetails = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.LibraryInAppDetails, com.github.yeriomin.playstoreapi.LibraryInAppDetails.Builder, com.github.yeriomin.playstoreapi.LibraryInAppDetailsOrBuilder> 
        getInAppDetailsFieldBuilder() {
      if (inAppDetailsBuilder_ == null) {
        inAppDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.LibraryInAppDetails, com.github.yeriomin.playstoreapi.LibraryInAppDetails.Builder, com.github.yeriomin.playstoreapi.LibraryInAppDetailsOrBuilder>(
                inAppDetails_,
                getParentForChildren(),
                isClean());
        inAppDetails_ = null;
      }
      return inAppDetailsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:LibraryMutation)
  }

  static {
    defaultInstance = new LibraryMutation(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:LibraryMutation)
}

