// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface LibraryDirtyDataOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 backend = 1;
  /**
   * <code>optional int32 backend = 1;</code>
   */
  boolean hasBackend();
  /**
   * <code>optional int32 backend = 1;</code>
   */
  int getBackend();
}
