// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface LibraryInAppDetailsOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string signedPurchaseData = 1;
  /**
   * <code>optional string signedPurchaseData = 1;</code>
   */
  boolean hasSignedPurchaseData();
  /**
   * <code>optional string signedPurchaseData = 1;</code>
   */
  java.lang.String getSignedPurchaseData();
  /**
   * <code>optional string signedPurchaseData = 1;</code>
   */
  com.google.protobuf.ByteString
      getSignedPurchaseDataBytes();

  // optional string signature = 2;
  /**
   * <code>optional string signature = 2;</code>
   */
  boolean hasSignature();
  /**
   * <code>optional string signature = 2;</code>
   */
  java.lang.String getSignature();
  /**
   * <code>optional string signature = 2;</code>
   */
  com.google.protobuf.ByteString
      getSignatureBytes();
}
