// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface MusicDetailsOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 censoring = 1;
  /**
   * <code>optional int32 censoring = 1;</code>
   */
  boolean hasCensoring();
  /**
   * <code>optional int32 censoring = 1;</code>
   */
  int getCensoring();

  // optional int32 durationSec = 2;
  /**
   * <code>optional int32 durationSec = 2;</code>
   */
  boolean hasDurationSec();
  /**
   * <code>optional int32 durationSec = 2;</code>
   */
  int getDurationSec();

  // optional string originalReleaseDate = 3;
  /**
   * <code>optional string originalReleaseDate = 3;</code>
   */
  boolean hasOriginalReleaseDate();
  /**
   * <code>optional string originalReleaseDate = 3;</code>
   */
  java.lang.String getOriginalReleaseDate();
  /**
   * <code>optional string originalReleaseDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getOriginalReleaseDateBytes();

  // optional string label = 4;
  /**
   * <code>optional string label = 4;</code>
   */
  boolean hasLabel();
  /**
   * <code>optional string label = 4;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>optional string label = 4;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  // repeated .ArtistDetails artist = 5;
  /**
   * <code>repeated .ArtistDetails artist = 5;</code>
   */
  java.util.List<com.github.yeriomin.playstoreapi.ArtistDetails> 
      getArtistList();
  /**
   * <code>repeated .ArtistDetails artist = 5;</code>
   */
  com.github.yeriomin.playstoreapi.ArtistDetails getArtist(int index);
  /**
   * <code>repeated .ArtistDetails artist = 5;</code>
   */
  int getArtistCount();
  /**
   * <code>repeated .ArtistDetails artist = 5;</code>
   */
  java.util.List<? extends com.github.yeriomin.playstoreapi.ArtistDetailsOrBuilder> 
      getArtistOrBuilderList();
  /**
   * <code>repeated .ArtistDetails artist = 5;</code>
   */
  com.github.yeriomin.playstoreapi.ArtistDetailsOrBuilder getArtistOrBuilder(
      int index);

  // repeated string genre = 6;
  /**
   * <code>repeated string genre = 6;</code>
   */
  java.util.List<java.lang.String>
  getGenreList();
  /**
   * <code>repeated string genre = 6;</code>
   */
  int getGenreCount();
  /**
   * <code>repeated string genre = 6;</code>
   */
  java.lang.String getGenre(int index);
  /**
   * <code>repeated string genre = 6;</code>
   */
  com.google.protobuf.ByteString
      getGenreBytes(int index);

  // optional string releaseDate = 7;
  /**
   * <code>optional string releaseDate = 7;</code>
   */
  boolean hasReleaseDate();
  /**
   * <code>optional string releaseDate = 7;</code>
   */
  java.lang.String getReleaseDate();
  /**
   * <code>optional string releaseDate = 7;</code>
   */
  com.google.protobuf.ByteString
      getReleaseDateBytes();

  // repeated int32 releaseType = 8;
  /**
   * <code>repeated int32 releaseType = 8;</code>
   */
  java.util.List<java.lang.Integer> getReleaseTypeList();
  /**
   * <code>repeated int32 releaseType = 8;</code>
   */
  int getReleaseTypeCount();
  /**
   * <code>repeated int32 releaseType = 8;</code>
   */
  int getReleaseType(int index);
}
