// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface PackageInfoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string pkgName = 1;
  /**
   * <code>optional string pkgName = 1;</code>
   */
  boolean hasPkgName();
  /**
   * <code>optional string pkgName = 1;</code>
   */
  java.lang.String getPkgName();
  /**
   * <code>optional string pkgName = 1;</code>
   */
  com.google.protobuf.ByteString
      getPkgNameBytes();

  // optional int32 versionCode = 2;
  /**
   * <code>optional int32 versionCode = 2;</code>
   */
  boolean hasVersionCode();
  /**
   * <code>optional int32 versionCode = 2;</code>
   */
  int getVersionCode();
}
