// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface PasswordPromptOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string prompt = 1;
  /**
   * <code>optional string prompt = 1;</code>
   */
  boolean hasPrompt();
  /**
   * <code>optional string prompt = 1;</code>
   */
  java.lang.String getPrompt();
  /**
   * <code>optional string prompt = 1;</code>
   */
  com.google.protobuf.ByteString
      getPromptBytes();

  // optional string forgotPasswordUrl = 2;
  /**
   * <code>optional string forgotPasswordUrl = 2;</code>
   */
  boolean hasForgotPasswordUrl();
  /**
   * <code>optional string forgotPasswordUrl = 2;</code>
   */
  java.lang.String getForgotPasswordUrl();
  /**
   * <code>optional string forgotPasswordUrl = 2;</code>
   */
  com.google.protobuf.ByteString
      getForgotPasswordUrlBytes();
}
