// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface PlusOneDataOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional bool setByUser = 1;
  /**
   * <code>optional bool setByUser = 1;</code>
   */
  boolean hasSetByUser();
  /**
   * <code>optional bool setByUser = 1;</code>
   */
  boolean getSetByUser();

  // optional int64 total = 2;
  /**
   * <code>optional int64 total = 2;</code>
   */
  boolean hasTotal();
  /**
   * <code>optional int64 total = 2;</code>
   */
  long getTotal();

  // optional int64 circlesTotal = 3;
  /**
   * <code>optional int64 circlesTotal = 3;</code>
   */
  boolean hasCirclesTotal();
  /**
   * <code>optional int64 circlesTotal = 3;</code>
   */
  long getCirclesTotal();

  // repeated .PlusPerson circlesPeople = 4;
  /**
   * <code>repeated .PlusPerson circlesPeople = 4;</code>
   */
  java.util.List<com.github.yeriomin.playstoreapi.PlusPerson> 
      getCirclesPeopleList();
  /**
   * <code>repeated .PlusPerson circlesPeople = 4;</code>
   */
  com.github.yeriomin.playstoreapi.PlusPerson getCirclesPeople(int index);
  /**
   * <code>repeated .PlusPerson circlesPeople = 4;</code>
   */
  int getCirclesPeopleCount();
  /**
   * <code>repeated .PlusPerson circlesPeople = 4;</code>
   */
  java.util.List<? extends com.github.yeriomin.playstoreapi.PlusPersonOrBuilder> 
      getCirclesPeopleOrBuilderList();
  /**
   * <code>repeated .PlusPerson circlesPeople = 4;</code>
   */
  com.github.yeriomin.playstoreapi.PlusPersonOrBuilder getCirclesPeopleOrBuilder(
      int index);
}
