// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface PurchaseRemovalDataOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional bool malicious = 1;
  /**
   * <code>optional bool malicious = 1;</code>
   */
  boolean hasMalicious();
  /**
   * <code>optional bool malicious = 1;</code>
   */
  boolean getMalicious();
}
