// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface RelatedLinksOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .RelatedLinksUnknown1 unknown1 = 10;
  /**
   * <code>optional .RelatedLinksUnknown1 unknown1 = 10;</code>
   */
  boolean hasUnknown1();
  /**
   * <code>optional .RelatedLinksUnknown1 unknown1 = 10;</code>
   */
  com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 getUnknown1();
  /**
   * <code>optional .RelatedLinksUnknown1 unknown1 = 10;</code>
   */
  com.github.yeriomin.playstoreapi.RelatedLinksUnknown1OrBuilder getUnknown1OrBuilder();

  // optional string privacyPolicyUrl = 18;
  /**
   * <code>optional string privacyPolicyUrl = 18;</code>
   */
  boolean hasPrivacyPolicyUrl();
  /**
   * <code>optional string privacyPolicyUrl = 18;</code>
   */
  java.lang.String getPrivacyPolicyUrl();
  /**
   * <code>optional string privacyPolicyUrl = 18;</code>
   */
  com.google.protobuf.ByteString
      getPrivacyPolicyUrlBytes();

  // optional .RelatedLink youMightAlsoLike = 24;
  /**
   * <code>optional .RelatedLink youMightAlsoLike = 24;</code>
   */
  boolean hasYouMightAlsoLike();
  /**
   * <code>optional .RelatedLink youMightAlsoLike = 24;</code>
   */
  com.github.yeriomin.playstoreapi.RelatedLink getYouMightAlsoLike();
  /**
   * <code>optional .RelatedLink youMightAlsoLike = 24;</code>
   */
  com.github.yeriomin.playstoreapi.RelatedLinkOrBuilder getYouMightAlsoLikeOrBuilder();

  // optional .Rated rated = 29;
  /**
   * <code>optional .Rated rated = 29;</code>
   */
  boolean hasRated();
  /**
   * <code>optional .Rated rated = 29;</code>
   */
  com.github.yeriomin.playstoreapi.Rated getRated();
  /**
   * <code>optional .Rated rated = 29;</code>
   */
  com.github.yeriomin.playstoreapi.RatedOrBuilder getRatedOrBuilder();

  // repeated .RelatedLink relatedLinks = 34;
  /**
   * <code>repeated .RelatedLink relatedLinks = 34;</code>
   */
  java.util.List<com.github.yeriomin.playstoreapi.RelatedLink> 
      getRelatedLinksList();
  /**
   * <code>repeated .RelatedLink relatedLinks = 34;</code>
   */
  com.github.yeriomin.playstoreapi.RelatedLink getRelatedLinks(int index);
  /**
   * <code>repeated .RelatedLink relatedLinks = 34;</code>
   */
  int getRelatedLinksCount();
  /**
   * <code>repeated .RelatedLink relatedLinks = 34;</code>
   */
  java.util.List<? extends com.github.yeriomin.playstoreapi.RelatedLinkOrBuilder> 
      getRelatedLinksOrBuilderList();
  /**
   * <code>repeated .RelatedLink relatedLinks = 34;</code>
   */
  com.github.yeriomin.playstoreapi.RelatedLinkOrBuilder getRelatedLinksOrBuilder(
      int index);

  // optional .CategoryInfo categoryInfo = 53;
  /**
   * <code>optional .CategoryInfo categoryInfo = 53;</code>
   */
  boolean hasCategoryInfo();
  /**
   * <code>optional .CategoryInfo categoryInfo = 53;</code>
   */
  com.github.yeriomin.playstoreapi.CategoryInfo getCategoryInfo();
  /**
   * <code>optional .CategoryInfo categoryInfo = 53;</code>
   */
  com.github.yeriomin.playstoreapi.CategoryInfoOrBuilder getCategoryInfoOrBuilder();
}
