// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface RelatedLinksUnknown1OrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .RelatedLinksUnknown2 unknown2 = 2;
  /**
   * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  boolean hasUnknown2();
  /**
   * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  com.github.yeriomin.playstoreapi.RelatedLinksUnknown2 getUnknown2();
  /**
   * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  com.github.yeriomin.playstoreapi.RelatedLinksUnknown2OrBuilder getUnknown2OrBuilder();
}
