// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

/**
 * Protobuf type {@code RuleEvaluation}
 */
public  final class RuleEvaluation extends
    com.google.protobuf.GeneratedMessage
    implements RuleEvaluationOrBuilder {
  // Use RuleEvaluation.newBuilder() to construct.
  private RuleEvaluation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private RuleEvaluation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final RuleEvaluation defaultInstance;
  public static RuleEvaluation getDefaultInstance() {
    return defaultInstance;
  }

  public RuleEvaluation getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private RuleEvaluation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.github.yeriomin.playstoreapi.Rule.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = rule_.toBuilder();
            }
            rule_ = input.readMessage(com.github.yeriomin.playstoreapi.Rule.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rule_);
              rule_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              actualStringValue_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            actualStringValue_.add(input.readBytes());
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              actualLongValue_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000004;
            }
            actualLongValue_.add(input.readInt64());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              actualLongValue_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              actualLongValue_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              actualBoolValue_ = new java.util.ArrayList<java.lang.Boolean>();
              mutable_bitField0_ |= 0x00000008;
            }
            actualBoolValue_.add(input.readBool());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
              actualBoolValue_ = new java.util.ArrayList<java.lang.Boolean>();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              actualBoolValue_.add(input.readBool());
            }
            input.popLimit(limit);
            break;
          }
          case 41: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              actualDoubleValue_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000010;
            }
            actualDoubleValue_.add(input.readDouble());
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
              actualDoubleValue_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000010;
            }
            while (input.getBytesUntilLimit() > 0) {
              actualDoubleValue_.add(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        actualStringValue_ = new com.google.protobuf.UnmodifiableLazyStringList(actualStringValue_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        actualLongValue_ = java.util.Collections.unmodifiableList(actualLongValue_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        actualBoolValue_ = java.util.Collections.unmodifiableList(actualBoolValue_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        actualDoubleValue_ = java.util.Collections.unmodifiableList(actualDoubleValue_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_RuleEvaluation_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_RuleEvaluation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.yeriomin.playstoreapi.RuleEvaluation.class, com.github.yeriomin.playstoreapi.RuleEvaluation.Builder.class);
  }

  public static com.google.protobuf.Parser<RuleEvaluation> PARSER =
      new com.google.protobuf.AbstractParser<RuleEvaluation>() {
    public RuleEvaluation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RuleEvaluation(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<RuleEvaluation> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional .Rule rule = 1;
  public static final int RULE_FIELD_NUMBER = 1;
  private com.github.yeriomin.playstoreapi.Rule rule_;
  /**
   * <code>optional .Rule rule = 1;</code>
   */
  public boolean hasRule() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .Rule rule = 1;</code>
   */
  public com.github.yeriomin.playstoreapi.Rule getRule() {
    return rule_;
  }
  /**
   * <code>optional .Rule rule = 1;</code>
   */
  public com.github.yeriomin.playstoreapi.RuleOrBuilder getRuleOrBuilder() {
    return rule_;
  }

  // repeated string actualStringValue = 2;
  public static final int ACTUALSTRINGVALUE_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList actualStringValue_;
  /**
   * <code>repeated string actualStringValue = 2;</code>
   */
  public java.util.List<java.lang.String>
      getActualStringValueList() {
    return actualStringValue_;
  }
  /**
   * <code>repeated string actualStringValue = 2;</code>
   */
  public int getActualStringValueCount() {
    return actualStringValue_.size();
  }
  /**
   * <code>repeated string actualStringValue = 2;</code>
   */
  public java.lang.String getActualStringValue(int index) {
    return actualStringValue_.get(index);
  }
  /**
   * <code>repeated string actualStringValue = 2;</code>
   */
  public com.google.protobuf.ByteString
      getActualStringValueBytes(int index) {
    return actualStringValue_.getByteString(index);
  }

  // repeated int64 actualLongValue = 3;
  public static final int ACTUALLONGVALUE_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Long> actualLongValue_;
  /**
   * <code>repeated int64 actualLongValue = 3;</code>
   */
  public java.util.List<java.lang.Long>
      getActualLongValueList() {
    return actualLongValue_;
  }
  /**
   * <code>repeated int64 actualLongValue = 3;</code>
   */
  public int getActualLongValueCount() {
    return actualLongValue_.size();
  }
  /**
   * <code>repeated int64 actualLongValue = 3;</code>
   */
  public long getActualLongValue(int index) {
    return actualLongValue_.get(index);
  }

  // repeated bool actualBoolValue = 4;
  public static final int ACTUALBOOLVALUE_FIELD_NUMBER = 4;
  private java.util.List<java.lang.Boolean> actualBoolValue_;
  /**
   * <code>repeated bool actualBoolValue = 4;</code>
   */
  public java.util.List<java.lang.Boolean>
      getActualBoolValueList() {
    return actualBoolValue_;
  }
  /**
   * <code>repeated bool actualBoolValue = 4;</code>
   */
  public int getActualBoolValueCount() {
    return actualBoolValue_.size();
  }
  /**
   * <code>repeated bool actualBoolValue = 4;</code>
   */
  public boolean getActualBoolValue(int index) {
    return actualBoolValue_.get(index);
  }

  // repeated double actualDoubleValue = 5;
  public static final int ACTUALDOUBLEVALUE_FIELD_NUMBER = 5;
  private java.util.List<java.lang.Double> actualDoubleValue_;
  /**
   * <code>repeated double actualDoubleValue = 5;</code>
   */
  public java.util.List<java.lang.Double>
      getActualDoubleValueList() {
    return actualDoubleValue_;
  }
  /**
   * <code>repeated double actualDoubleValue = 5;</code>
   */
  public int getActualDoubleValueCount() {
    return actualDoubleValue_.size();
  }
  /**
   * <code>repeated double actualDoubleValue = 5;</code>
   */
  public double getActualDoubleValue(int index) {
    return actualDoubleValue_.get(index);
  }

  private void initFields() {
    rule_ = com.github.yeriomin.playstoreapi.Rule.getDefaultInstance();
    actualStringValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    actualLongValue_ = java.util.Collections.emptyList();
    actualBoolValue_ = java.util.Collections.emptyList();
    actualDoubleValue_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, rule_);
    }
    for (int i = 0; i < actualStringValue_.size(); i++) {
      output.writeBytes(2, actualStringValue_.getByteString(i));
    }
    for (int i = 0; i < actualLongValue_.size(); i++) {
      output.writeInt64(3, actualLongValue_.get(i));
    }
    for (int i = 0; i < actualBoolValue_.size(); i++) {
      output.writeBool(4, actualBoolValue_.get(i));
    }
    for (int i = 0; i < actualDoubleValue_.size(); i++) {
      output.writeDouble(5, actualDoubleValue_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rule_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < actualStringValue_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(actualStringValue_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getActualStringValueList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < actualLongValue_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(actualLongValue_.get(i));
      }
      size += dataSize;
      size += 1 * getActualLongValueList().size();
    }
    {
      int dataSize = 0;
      dataSize = 1 * getActualBoolValueList().size();
      size += dataSize;
      size += 1 * getActualBoolValueList().size();
    }
    {
      int dataSize = 0;
      dataSize = 8 * getActualDoubleValueList().size();
      size += dataSize;
      size += 1 * getActualDoubleValueList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.github.yeriomin.playstoreapi.RuleEvaluation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.yeriomin.playstoreapi.RuleEvaluation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.RuleEvaluation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.yeriomin.playstoreapi.RuleEvaluation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.RuleEvaluation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.RuleEvaluation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.RuleEvaluation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.RuleEvaluation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.RuleEvaluation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.RuleEvaluation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.github.yeriomin.playstoreapi.RuleEvaluation prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RuleEvaluation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.github.yeriomin.playstoreapi.RuleEvaluationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_RuleEvaluation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_RuleEvaluation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.yeriomin.playstoreapi.RuleEvaluation.class, com.github.yeriomin.playstoreapi.RuleEvaluation.Builder.class);
    }

    // Construct using com.github.yeriomin.playstoreapi.RuleEvaluation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getRuleFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (ruleBuilder_ == null) {
        rule_ = com.github.yeriomin.playstoreapi.Rule.getDefaultInstance();
      } else {
        ruleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      actualStringValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      actualLongValue_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      actualBoolValue_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      actualDoubleValue_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_RuleEvaluation_descriptor;
    }

    public com.github.yeriomin.playstoreapi.RuleEvaluation getDefaultInstanceForType() {
      return com.github.yeriomin.playstoreapi.RuleEvaluation.getDefaultInstance();
    }

    public com.github.yeriomin.playstoreapi.RuleEvaluation build() {
      com.github.yeriomin.playstoreapi.RuleEvaluation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.yeriomin.playstoreapi.RuleEvaluation buildPartial() {
      com.github.yeriomin.playstoreapi.RuleEvaluation result = new com.github.yeriomin.playstoreapi.RuleEvaluation(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (ruleBuilder_ == null) {
        result.rule_ = rule_;
      } else {
        result.rule_ = ruleBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        actualStringValue_ = new com.google.protobuf.UnmodifiableLazyStringList(
            actualStringValue_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.actualStringValue_ = actualStringValue_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        actualLongValue_ = java.util.Collections.unmodifiableList(actualLongValue_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.actualLongValue_ = actualLongValue_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        actualBoolValue_ = java.util.Collections.unmodifiableList(actualBoolValue_);
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.actualBoolValue_ = actualBoolValue_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        actualDoubleValue_ = java.util.Collections.unmodifiableList(actualDoubleValue_);
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.actualDoubleValue_ = actualDoubleValue_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.yeriomin.playstoreapi.RuleEvaluation) {
        return mergeFrom((com.github.yeriomin.playstoreapi.RuleEvaluation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.yeriomin.playstoreapi.RuleEvaluation other) {
      if (other == com.github.yeriomin.playstoreapi.RuleEvaluation.getDefaultInstance()) return this;
      if (other.hasRule()) {
        mergeRule(other.getRule());
      }
      if (!other.actualStringValue_.isEmpty()) {
        if (actualStringValue_.isEmpty()) {
          actualStringValue_ = other.actualStringValue_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureActualStringValueIsMutable();
          actualStringValue_.addAll(other.actualStringValue_);
        }
        onChanged();
      }
      if (!other.actualLongValue_.isEmpty()) {
        if (actualLongValue_.isEmpty()) {
          actualLongValue_ = other.actualLongValue_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureActualLongValueIsMutable();
          actualLongValue_.addAll(other.actualLongValue_);
        }
        onChanged();
      }
      if (!other.actualBoolValue_.isEmpty()) {
        if (actualBoolValue_.isEmpty()) {
          actualBoolValue_ = other.actualBoolValue_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureActualBoolValueIsMutable();
          actualBoolValue_.addAll(other.actualBoolValue_);
        }
        onChanged();
      }
      if (!other.actualDoubleValue_.isEmpty()) {
        if (actualDoubleValue_.isEmpty()) {
          actualDoubleValue_ = other.actualDoubleValue_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureActualDoubleValueIsMutable();
          actualDoubleValue_.addAll(other.actualDoubleValue_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.yeriomin.playstoreapi.RuleEvaluation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.yeriomin.playstoreapi.RuleEvaluation) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional .Rule rule = 1;
    private com.github.yeriomin.playstoreapi.Rule rule_ = com.github.yeriomin.playstoreapi.Rule.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.Rule, com.github.yeriomin.playstoreapi.Rule.Builder, com.github.yeriomin.playstoreapi.RuleOrBuilder> ruleBuilder_;
    /**
     * <code>optional .Rule rule = 1;</code>
     */
    public boolean hasRule() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Rule rule = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.Rule getRule() {
      if (ruleBuilder_ == null) {
        return rule_;
      } else {
        return ruleBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Rule rule = 1;</code>
     */
    public Builder setRule(com.github.yeriomin.playstoreapi.Rule value) {
      if (ruleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rule_ = value;
        onChanged();
      } else {
        ruleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .Rule rule = 1;</code>
     */
    public Builder setRule(
        com.github.yeriomin.playstoreapi.Rule.Builder builderForValue) {
      if (ruleBuilder_ == null) {
        rule_ = builderForValue.build();
        onChanged();
      } else {
        ruleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .Rule rule = 1;</code>
     */
    public Builder mergeRule(com.github.yeriomin.playstoreapi.Rule value) {
      if (ruleBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            rule_ != com.github.yeriomin.playstoreapi.Rule.getDefaultInstance()) {
          rule_ =
            com.github.yeriomin.playstoreapi.Rule.newBuilder(rule_).mergeFrom(value).buildPartial();
        } else {
          rule_ = value;
        }
        onChanged();
      } else {
        ruleBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .Rule rule = 1;</code>
     */
    public Builder clearRule() {
      if (ruleBuilder_ == null) {
        rule_ = com.github.yeriomin.playstoreapi.Rule.getDefaultInstance();
        onChanged();
      } else {
        ruleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .Rule rule = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.Rule.Builder getRuleBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRuleFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Rule rule = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.RuleOrBuilder getRuleOrBuilder() {
      if (ruleBuilder_ != null) {
        return ruleBuilder_.getMessageOrBuilder();
      } else {
        return rule_;
      }
    }
    /**
     * <code>optional .Rule rule = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.Rule, com.github.yeriomin.playstoreapi.Rule.Builder, com.github.yeriomin.playstoreapi.RuleOrBuilder> 
        getRuleFieldBuilder() {
      if (ruleBuilder_ == null) {
        ruleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.Rule, com.github.yeriomin.playstoreapi.Rule.Builder, com.github.yeriomin.playstoreapi.RuleOrBuilder>(
                rule_,
                getParentForChildren(),
                isClean());
        rule_ = null;
      }
      return ruleBuilder_;
    }

    // repeated string actualStringValue = 2;
    private com.google.protobuf.LazyStringList actualStringValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureActualStringValueIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        actualStringValue_ = new com.google.protobuf.LazyStringArrayList(actualStringValue_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string actualStringValue = 2;</code>
     */
    public java.util.List<java.lang.String>
        getActualStringValueList() {
      return java.util.Collections.unmodifiableList(actualStringValue_);
    }
    /**
     * <code>repeated string actualStringValue = 2;</code>
     */
    public int getActualStringValueCount() {
      return actualStringValue_.size();
    }
    /**
     * <code>repeated string actualStringValue = 2;</code>
     */
    public java.lang.String getActualStringValue(int index) {
      return actualStringValue_.get(index);
    }
    /**
     * <code>repeated string actualStringValue = 2;</code>
     */
    public com.google.protobuf.ByteString
        getActualStringValueBytes(int index) {
      return actualStringValue_.getByteString(index);
    }
    /**
     * <code>repeated string actualStringValue = 2;</code>
     */
    public Builder setActualStringValue(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureActualStringValueIsMutable();
      actualStringValue_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string actualStringValue = 2;</code>
     */
    public Builder addActualStringValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureActualStringValueIsMutable();
      actualStringValue_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string actualStringValue = 2;</code>
     */
    public Builder addAllActualStringValue(
        java.lang.Iterable<java.lang.String> values) {
      ensureActualStringValueIsMutable();
      super.addAll(values, actualStringValue_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string actualStringValue = 2;</code>
     */
    public Builder clearActualStringValue() {
      actualStringValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string actualStringValue = 2;</code>
     */
    public Builder addActualStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureActualStringValueIsMutable();
      actualStringValue_.add(value);
      onChanged();
      return this;
    }

    // repeated int64 actualLongValue = 3;
    private java.util.List<java.lang.Long> actualLongValue_ = java.util.Collections.emptyList();
    private void ensureActualLongValueIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        actualLongValue_ = new java.util.ArrayList<java.lang.Long>(actualLongValue_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int64 actualLongValue = 3;</code>
     */
    public java.util.List<java.lang.Long>
        getActualLongValueList() {
      return java.util.Collections.unmodifiableList(actualLongValue_);
    }
    /**
     * <code>repeated int64 actualLongValue = 3;</code>
     */
    public int getActualLongValueCount() {
      return actualLongValue_.size();
    }
    /**
     * <code>repeated int64 actualLongValue = 3;</code>
     */
    public long getActualLongValue(int index) {
      return actualLongValue_.get(index);
    }
    /**
     * <code>repeated int64 actualLongValue = 3;</code>
     */
    public Builder setActualLongValue(
        int index, long value) {
      ensureActualLongValueIsMutable();
      actualLongValue_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 actualLongValue = 3;</code>
     */
    public Builder addActualLongValue(long value) {
      ensureActualLongValueIsMutable();
      actualLongValue_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 actualLongValue = 3;</code>
     */
    public Builder addAllActualLongValue(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureActualLongValueIsMutable();
      super.addAll(values, actualLongValue_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 actualLongValue = 3;</code>
     */
    public Builder clearActualLongValue() {
      actualLongValue_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    // repeated bool actualBoolValue = 4;
    private java.util.List<java.lang.Boolean> actualBoolValue_ = java.util.Collections.emptyList();
    private void ensureActualBoolValueIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        actualBoolValue_ = new java.util.ArrayList<java.lang.Boolean>(actualBoolValue_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated bool actualBoolValue = 4;</code>
     */
    public java.util.List<java.lang.Boolean>
        getActualBoolValueList() {
      return java.util.Collections.unmodifiableList(actualBoolValue_);
    }
    /**
     * <code>repeated bool actualBoolValue = 4;</code>
     */
    public int getActualBoolValueCount() {
      return actualBoolValue_.size();
    }
    /**
     * <code>repeated bool actualBoolValue = 4;</code>
     */
    public boolean getActualBoolValue(int index) {
      return actualBoolValue_.get(index);
    }
    /**
     * <code>repeated bool actualBoolValue = 4;</code>
     */
    public Builder setActualBoolValue(
        int index, boolean value) {
      ensureActualBoolValueIsMutable();
      actualBoolValue_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool actualBoolValue = 4;</code>
     */
    public Builder addActualBoolValue(boolean value) {
      ensureActualBoolValueIsMutable();
      actualBoolValue_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool actualBoolValue = 4;</code>
     */
    public Builder addAllActualBoolValue(
        java.lang.Iterable<? extends java.lang.Boolean> values) {
      ensureActualBoolValueIsMutable();
      super.addAll(values, actualBoolValue_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool actualBoolValue = 4;</code>
     */
    public Builder clearActualBoolValue() {
      actualBoolValue_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    // repeated double actualDoubleValue = 5;
    private java.util.List<java.lang.Double> actualDoubleValue_ = java.util.Collections.emptyList();
    private void ensureActualDoubleValueIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        actualDoubleValue_ = new java.util.ArrayList<java.lang.Double>(actualDoubleValue_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated double actualDoubleValue = 5;</code>
     */
    public java.util.List<java.lang.Double>
        getActualDoubleValueList() {
      return java.util.Collections.unmodifiableList(actualDoubleValue_);
    }
    /**
     * <code>repeated double actualDoubleValue = 5;</code>
     */
    public int getActualDoubleValueCount() {
      return actualDoubleValue_.size();
    }
    /**
     * <code>repeated double actualDoubleValue = 5;</code>
     */
    public double getActualDoubleValue(int index) {
      return actualDoubleValue_.get(index);
    }
    /**
     * <code>repeated double actualDoubleValue = 5;</code>
     */
    public Builder setActualDoubleValue(
        int index, double value) {
      ensureActualDoubleValueIsMutable();
      actualDoubleValue_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double actualDoubleValue = 5;</code>
     */
    public Builder addActualDoubleValue(double value) {
      ensureActualDoubleValueIsMutable();
      actualDoubleValue_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double actualDoubleValue = 5;</code>
     */
    public Builder addAllActualDoubleValue(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureActualDoubleValueIsMutable();
      super.addAll(values, actualDoubleValue_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double actualDoubleValue = 5;</code>
     */
    public Builder clearActualDoubleValue() {
      actualDoubleValue_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RuleEvaluation)
  }

  static {
    defaultInstance = new RuleEvaluation(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:RuleEvaluation)
}

