// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface SearchResponseOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string originalQuery = 1;
  /**
   * <code>optional string originalQuery = 1;</code>
   */
  boolean hasOriginalQuery();
  /**
   * <code>optional string originalQuery = 1;</code>
   */
  java.lang.String getOriginalQuery();
  /**
   * <code>optional string originalQuery = 1;</code>
   */
  com.google.protobuf.ByteString
      getOriginalQueryBytes();

  // optional string suggestedQuery = 2;
  /**
   * <code>optional string suggestedQuery = 2;</code>
   */
  boolean hasSuggestedQuery();
  /**
   * <code>optional string suggestedQuery = 2;</code>
   */
  java.lang.String getSuggestedQuery();
  /**
   * <code>optional string suggestedQuery = 2;</code>
   */
  com.google.protobuf.ByteString
      getSuggestedQueryBytes();

  // optional bool aggregateQuery = 3;
  /**
   * <code>optional bool aggregateQuery = 3;</code>
   */
  boolean hasAggregateQuery();
  /**
   * <code>optional bool aggregateQuery = 3;</code>
   */
  boolean getAggregateQuery();

  // repeated .Bucket bucket = 4;
  /**
   * <code>repeated .Bucket bucket = 4;</code>
   */
  java.util.List<com.github.yeriomin.playstoreapi.Bucket> 
      getBucketList();
  /**
   * <code>repeated .Bucket bucket = 4;</code>
   */
  com.github.yeriomin.playstoreapi.Bucket getBucket(int index);
  /**
   * <code>repeated .Bucket bucket = 4;</code>
   */
  int getBucketCount();
  /**
   * <code>repeated .Bucket bucket = 4;</code>
   */
  java.util.List<? extends com.github.yeriomin.playstoreapi.BucketOrBuilder> 
      getBucketOrBuilderList();
  /**
   * <code>repeated .Bucket bucket = 4;</code>
   */
  com.github.yeriomin.playstoreapi.BucketOrBuilder getBucketOrBuilder(
      int index);

  // repeated .DocV2 doc = 5;
  /**
   * <code>repeated .DocV2 doc = 5;</code>
   */
  java.util.List<com.github.yeriomin.playstoreapi.DocV2> 
      getDocList();
  /**
   * <code>repeated .DocV2 doc = 5;</code>
   */
  com.github.yeriomin.playstoreapi.DocV2 getDoc(int index);
  /**
   * <code>repeated .DocV2 doc = 5;</code>
   */
  int getDocCount();
  /**
   * <code>repeated .DocV2 doc = 5;</code>
   */
  java.util.List<? extends com.github.yeriomin.playstoreapi.DocV2OrBuilder> 
      getDocOrBuilderList();
  /**
   * <code>repeated .DocV2 doc = 5;</code>
   */
  com.github.yeriomin.playstoreapi.DocV2OrBuilder getDocOrBuilder(
      int index);

  // repeated .RelatedSearch relatedSearch = 6;
  /**
   * <code>repeated .RelatedSearch relatedSearch = 6;</code>
   */
  java.util.List<com.github.yeriomin.playstoreapi.RelatedSearch> 
      getRelatedSearchList();
  /**
   * <code>repeated .RelatedSearch relatedSearch = 6;</code>
   */
  com.github.yeriomin.playstoreapi.RelatedSearch getRelatedSearch(int index);
  /**
   * <code>repeated .RelatedSearch relatedSearch = 6;</code>
   */
  int getRelatedSearchCount();
  /**
   * <code>repeated .RelatedSearch relatedSearch = 6;</code>
   */
  java.util.List<? extends com.github.yeriomin.playstoreapi.RelatedSearchOrBuilder> 
      getRelatedSearchOrBuilderList();
  /**
   * <code>repeated .RelatedSearch relatedSearch = 6;</code>
   */
  com.github.yeriomin.playstoreapi.RelatedSearchOrBuilder getRelatedSearchOrBuilder(
      int index);

  // optional string nextPageUrl = 10;
  /**
   * <code>optional string nextPageUrl = 10;</code>
   */
  boolean hasNextPageUrl();
  /**
   * <code>optional string nextPageUrl = 10;</code>
   */
  java.lang.String getNextPageUrl();
  /**
   * <code>optional string nextPageUrl = 10;</code>
   */
  com.google.protobuf.ByteString
      getNextPageUrlBytes();
}
