// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface SongDetailsOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string name = 1;
  /**
   * <code>optional string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // optional .MusicDetails details = 2;
  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  boolean hasDetails();
  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  com.github.yeriomin.playstoreapi.MusicDetails getDetails();
  /**
   * <code>optional .MusicDetails details = 2;</code>
   */
  com.github.yeriomin.playstoreapi.MusicDetailsOrBuilder getDetailsOrBuilder();

  // optional string albumName = 3;
  /**
   * <code>optional string albumName = 3;</code>
   */
  boolean hasAlbumName();
  /**
   * <code>optional string albumName = 3;</code>
   */
  java.lang.String getAlbumName();
  /**
   * <code>optional string albumName = 3;</code>
   */
  com.google.protobuf.ByteString
      getAlbumNameBytes();

  // optional int32 trackNumber = 4;
  /**
   * <code>optional int32 trackNumber = 4;</code>
   */
  boolean hasTrackNumber();
  /**
   * <code>optional int32 trackNumber = 4;</code>
   */
  int getTrackNumber();

  // optional string previewUrl = 5;
  /**
   * <code>optional string previewUrl = 5;</code>
   */
  boolean hasPreviewUrl();
  /**
   * <code>optional string previewUrl = 5;</code>
   */
  java.lang.String getPreviewUrl();
  /**
   * <code>optional string previewUrl = 5;</code>
   */
  com.google.protobuf.ByteString
      getPreviewUrlBytes();

  // optional .ArtistDetails displayArtist = 6;
  /**
   * <code>optional .ArtistDetails displayArtist = 6;</code>
   */
  boolean hasDisplayArtist();
  /**
   * <code>optional .ArtistDetails displayArtist = 6;</code>
   */
  com.github.yeriomin.playstoreapi.ArtistDetails getDisplayArtist();
  /**
   * <code>optional .ArtistDetails displayArtist = 6;</code>
   */
  com.github.yeriomin.playstoreapi.ArtistDetailsOrBuilder getDisplayArtistOrBuilder();
}
