// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

/**
 * Protobuf type {@code SubscriptionTerms}
 */
public  final class SubscriptionTerms extends
    com.google.protobuf.GeneratedMessage
    implements SubscriptionTermsOrBuilder {
  // Use SubscriptionTerms.newBuilder() to construct.
  private SubscriptionTerms(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private SubscriptionTerms(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final SubscriptionTerms defaultInstance;
  public static SubscriptionTerms getDefaultInstance() {
    return defaultInstance;
  }

  public SubscriptionTerms getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private SubscriptionTerms(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.github.yeriomin.playstoreapi.TimePeriod.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = recurringPeriod_.toBuilder();
            }
            recurringPeriod_ = input.readMessage(com.github.yeriomin.playstoreapi.TimePeriod.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(recurringPeriod_);
              recurringPeriod_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            com.github.yeriomin.playstoreapi.TimePeriod.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = trialPeriod_.toBuilder();
            }
            trialPeriod_ = input.readMessage(com.github.yeriomin.playstoreapi.TimePeriod.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(trialPeriod_);
              trialPeriod_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_SubscriptionTerms_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_SubscriptionTerms_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.yeriomin.playstoreapi.SubscriptionTerms.class, com.github.yeriomin.playstoreapi.SubscriptionTerms.Builder.class);
  }

  public static com.google.protobuf.Parser<SubscriptionTerms> PARSER =
      new com.google.protobuf.AbstractParser<SubscriptionTerms>() {
    public SubscriptionTerms parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SubscriptionTerms(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<SubscriptionTerms> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional .TimePeriod recurringPeriod = 1;
  public static final int RECURRINGPERIOD_FIELD_NUMBER = 1;
  private com.github.yeriomin.playstoreapi.TimePeriod recurringPeriod_;
  /**
   * <code>optional .TimePeriod recurringPeriod = 1;</code>
   */
  public boolean hasRecurringPeriod() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .TimePeriod recurringPeriod = 1;</code>
   */
  public com.github.yeriomin.playstoreapi.TimePeriod getRecurringPeriod() {
    return recurringPeriod_;
  }
  /**
   * <code>optional .TimePeriod recurringPeriod = 1;</code>
   */
  public com.github.yeriomin.playstoreapi.TimePeriodOrBuilder getRecurringPeriodOrBuilder() {
    return recurringPeriod_;
  }

  // optional .TimePeriod trialPeriod = 2;
  public static final int TRIALPERIOD_FIELD_NUMBER = 2;
  private com.github.yeriomin.playstoreapi.TimePeriod trialPeriod_;
  /**
   * <code>optional .TimePeriod trialPeriod = 2;</code>
   */
  public boolean hasTrialPeriod() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .TimePeriod trialPeriod = 2;</code>
   */
  public com.github.yeriomin.playstoreapi.TimePeriod getTrialPeriod() {
    return trialPeriod_;
  }
  /**
   * <code>optional .TimePeriod trialPeriod = 2;</code>
   */
  public com.github.yeriomin.playstoreapi.TimePeriodOrBuilder getTrialPeriodOrBuilder() {
    return trialPeriod_;
  }

  private void initFields() {
    recurringPeriod_ = com.github.yeriomin.playstoreapi.TimePeriod.getDefaultInstance();
    trialPeriod_ = com.github.yeriomin.playstoreapi.TimePeriod.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, recurringPeriod_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, trialPeriod_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, recurringPeriod_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, trialPeriod_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.github.yeriomin.playstoreapi.SubscriptionTerms parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.yeriomin.playstoreapi.SubscriptionTerms parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.SubscriptionTerms parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.yeriomin.playstoreapi.SubscriptionTerms parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.SubscriptionTerms parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.SubscriptionTerms parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.SubscriptionTerms parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.SubscriptionTerms parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.SubscriptionTerms parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.github.yeriomin.playstoreapi.SubscriptionTerms parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.github.yeriomin.playstoreapi.SubscriptionTerms prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SubscriptionTerms}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.github.yeriomin.playstoreapi.SubscriptionTermsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_SubscriptionTerms_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_SubscriptionTerms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.yeriomin.playstoreapi.SubscriptionTerms.class, com.github.yeriomin.playstoreapi.SubscriptionTerms.Builder.class);
    }

    // Construct using com.github.yeriomin.playstoreapi.SubscriptionTerms.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getRecurringPeriodFieldBuilder();
        getTrialPeriodFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (recurringPeriodBuilder_ == null) {
        recurringPeriod_ = com.github.yeriomin.playstoreapi.TimePeriod.getDefaultInstance();
      } else {
        recurringPeriodBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (trialPeriodBuilder_ == null) {
        trialPeriod_ = com.github.yeriomin.playstoreapi.TimePeriod.getDefaultInstance();
      } else {
        trialPeriodBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.yeriomin.playstoreapi.GooglePlay.internal_static_SubscriptionTerms_descriptor;
    }

    public com.github.yeriomin.playstoreapi.SubscriptionTerms getDefaultInstanceForType() {
      return com.github.yeriomin.playstoreapi.SubscriptionTerms.getDefaultInstance();
    }

    public com.github.yeriomin.playstoreapi.SubscriptionTerms build() {
      com.github.yeriomin.playstoreapi.SubscriptionTerms result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.yeriomin.playstoreapi.SubscriptionTerms buildPartial() {
      com.github.yeriomin.playstoreapi.SubscriptionTerms result = new com.github.yeriomin.playstoreapi.SubscriptionTerms(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (recurringPeriodBuilder_ == null) {
        result.recurringPeriod_ = recurringPeriod_;
      } else {
        result.recurringPeriod_ = recurringPeriodBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (trialPeriodBuilder_ == null) {
        result.trialPeriod_ = trialPeriod_;
      } else {
        result.trialPeriod_ = trialPeriodBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.yeriomin.playstoreapi.SubscriptionTerms) {
        return mergeFrom((com.github.yeriomin.playstoreapi.SubscriptionTerms)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.yeriomin.playstoreapi.SubscriptionTerms other) {
      if (other == com.github.yeriomin.playstoreapi.SubscriptionTerms.getDefaultInstance()) return this;
      if (other.hasRecurringPeriod()) {
        mergeRecurringPeriod(other.getRecurringPeriod());
      }
      if (other.hasTrialPeriod()) {
        mergeTrialPeriod(other.getTrialPeriod());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.yeriomin.playstoreapi.SubscriptionTerms parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.yeriomin.playstoreapi.SubscriptionTerms) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional .TimePeriod recurringPeriod = 1;
    private com.github.yeriomin.playstoreapi.TimePeriod recurringPeriod_ = com.github.yeriomin.playstoreapi.TimePeriod.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.TimePeriod, com.github.yeriomin.playstoreapi.TimePeriod.Builder, com.github.yeriomin.playstoreapi.TimePeriodOrBuilder> recurringPeriodBuilder_;
    /**
     * <code>optional .TimePeriod recurringPeriod = 1;</code>
     */
    public boolean hasRecurringPeriod() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .TimePeriod recurringPeriod = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.TimePeriod getRecurringPeriod() {
      if (recurringPeriodBuilder_ == null) {
        return recurringPeriod_;
      } else {
        return recurringPeriodBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .TimePeriod recurringPeriod = 1;</code>
     */
    public Builder setRecurringPeriod(com.github.yeriomin.playstoreapi.TimePeriod value) {
      if (recurringPeriodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        recurringPeriod_ = value;
        onChanged();
      } else {
        recurringPeriodBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .TimePeriod recurringPeriod = 1;</code>
     */
    public Builder setRecurringPeriod(
        com.github.yeriomin.playstoreapi.TimePeriod.Builder builderForValue) {
      if (recurringPeriodBuilder_ == null) {
        recurringPeriod_ = builderForValue.build();
        onChanged();
      } else {
        recurringPeriodBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .TimePeriod recurringPeriod = 1;</code>
     */
    public Builder mergeRecurringPeriod(com.github.yeriomin.playstoreapi.TimePeriod value) {
      if (recurringPeriodBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            recurringPeriod_ != com.github.yeriomin.playstoreapi.TimePeriod.getDefaultInstance()) {
          recurringPeriod_ =
            com.github.yeriomin.playstoreapi.TimePeriod.newBuilder(recurringPeriod_).mergeFrom(value).buildPartial();
        } else {
          recurringPeriod_ = value;
        }
        onChanged();
      } else {
        recurringPeriodBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .TimePeriod recurringPeriod = 1;</code>
     */
    public Builder clearRecurringPeriod() {
      if (recurringPeriodBuilder_ == null) {
        recurringPeriod_ = com.github.yeriomin.playstoreapi.TimePeriod.getDefaultInstance();
        onChanged();
      } else {
        recurringPeriodBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .TimePeriod recurringPeriod = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.TimePeriod.Builder getRecurringPeriodBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRecurringPeriodFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .TimePeriod recurringPeriod = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.TimePeriodOrBuilder getRecurringPeriodOrBuilder() {
      if (recurringPeriodBuilder_ != null) {
        return recurringPeriodBuilder_.getMessageOrBuilder();
      } else {
        return recurringPeriod_;
      }
    }
    /**
     * <code>optional .TimePeriod recurringPeriod = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.TimePeriod, com.github.yeriomin.playstoreapi.TimePeriod.Builder, com.github.yeriomin.playstoreapi.TimePeriodOrBuilder> 
        getRecurringPeriodFieldBuilder() {
      if (recurringPeriodBuilder_ == null) {
        recurringPeriodBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.TimePeriod, com.github.yeriomin.playstoreapi.TimePeriod.Builder, com.github.yeriomin.playstoreapi.TimePeriodOrBuilder>(
                recurringPeriod_,
                getParentForChildren(),
                isClean());
        recurringPeriod_ = null;
      }
      return recurringPeriodBuilder_;
    }

    // optional .TimePeriod trialPeriod = 2;
    private com.github.yeriomin.playstoreapi.TimePeriod trialPeriod_ = com.github.yeriomin.playstoreapi.TimePeriod.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.TimePeriod, com.github.yeriomin.playstoreapi.TimePeriod.Builder, com.github.yeriomin.playstoreapi.TimePeriodOrBuilder> trialPeriodBuilder_;
    /**
     * <code>optional .TimePeriod trialPeriod = 2;</code>
     */
    public boolean hasTrialPeriod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .TimePeriod trialPeriod = 2;</code>
     */
    public com.github.yeriomin.playstoreapi.TimePeriod getTrialPeriod() {
      if (trialPeriodBuilder_ == null) {
        return trialPeriod_;
      } else {
        return trialPeriodBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .TimePeriod trialPeriod = 2;</code>
     */
    public Builder setTrialPeriod(com.github.yeriomin.playstoreapi.TimePeriod value) {
      if (trialPeriodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trialPeriod_ = value;
        onChanged();
      } else {
        trialPeriodBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .TimePeriod trialPeriod = 2;</code>
     */
    public Builder setTrialPeriod(
        com.github.yeriomin.playstoreapi.TimePeriod.Builder builderForValue) {
      if (trialPeriodBuilder_ == null) {
        trialPeriod_ = builderForValue.build();
        onChanged();
      } else {
        trialPeriodBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .TimePeriod trialPeriod = 2;</code>
     */
    public Builder mergeTrialPeriod(com.github.yeriomin.playstoreapi.TimePeriod value) {
      if (trialPeriodBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            trialPeriod_ != com.github.yeriomin.playstoreapi.TimePeriod.getDefaultInstance()) {
          trialPeriod_ =
            com.github.yeriomin.playstoreapi.TimePeriod.newBuilder(trialPeriod_).mergeFrom(value).buildPartial();
        } else {
          trialPeriod_ = value;
        }
        onChanged();
      } else {
        trialPeriodBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .TimePeriod trialPeriod = 2;</code>
     */
    public Builder clearTrialPeriod() {
      if (trialPeriodBuilder_ == null) {
        trialPeriod_ = com.github.yeriomin.playstoreapi.TimePeriod.getDefaultInstance();
        onChanged();
      } else {
        trialPeriodBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .TimePeriod trialPeriod = 2;</code>
     */
    public com.github.yeriomin.playstoreapi.TimePeriod.Builder getTrialPeriodBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTrialPeriodFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .TimePeriod trialPeriod = 2;</code>
     */
    public com.github.yeriomin.playstoreapi.TimePeriodOrBuilder getTrialPeriodOrBuilder() {
      if (trialPeriodBuilder_ != null) {
        return trialPeriodBuilder_.getMessageOrBuilder();
      } else {
        return trialPeriod_;
      }
    }
    /**
     * <code>optional .TimePeriod trialPeriod = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.yeriomin.playstoreapi.TimePeriod, com.github.yeriomin.playstoreapi.TimePeriod.Builder, com.github.yeriomin.playstoreapi.TimePeriodOrBuilder> 
        getTrialPeriodFieldBuilder() {
      if (trialPeriodBuilder_ == null) {
        trialPeriodBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.yeriomin.playstoreapi.TimePeriod, com.github.yeriomin.playstoreapi.TimePeriod.Builder, com.github.yeriomin.playstoreapi.TimePeriodOrBuilder>(
                trialPeriod_,
                getParentForChildren(),
                isClean());
        trialPeriod_ = null;
      }
      return trialPeriodBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:SubscriptionTerms)
  }

  static {
    defaultInstance = new SubscriptionTerms(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:SubscriptionTerms)
}

