// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface TimePeriodOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 unit = 1;
  /**
   * <code>optional int32 unit = 1;</code>
   */
  boolean hasUnit();
  /**
   * <code>optional int32 unit = 1;</code>
   */
  int getUnit();

  // optional int32 count = 2;
  /**
   * <code>optional int32 count = 2;</code>
   */
  boolean hasCount();
  /**
   * <code>optional int32 count = 2;</code>
   */
  int getCount();
}
