// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface Unknown25OrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated .Unknown25Item item = 2;
  /**
   * <code>repeated .Unknown25Item item = 2;</code>
   */
  java.util.List<com.github.yeriomin.playstoreapi.Unknown25Item> 
      getItemList();
  /**
   * <code>repeated .Unknown25Item item = 2;</code>
   */
  com.github.yeriomin.playstoreapi.Unknown25Item getItem(int index);
  /**
   * <code>repeated .Unknown25Item item = 2;</code>
   */
  int getItemCount();
  /**
   * <code>repeated .Unknown25Item item = 2;</code>
   */
  java.util.List<? extends com.github.yeriomin.playstoreapi.Unknown25ItemOrBuilder> 
      getItemOrBuilderList();
  /**
   * <code>repeated .Unknown25Item item = 2;</code>
   */
  com.github.yeriomin.playstoreapi.Unknown25ItemOrBuilder getItemOrBuilder(
      int index);
}
