// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface UploadDeviceConfigResponseOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string uploadDeviceConfigToken = 1;
  /**
   * <code>optional string uploadDeviceConfigToken = 1;</code>
   */
  boolean hasUploadDeviceConfigToken();
  /**
   * <code>optional string uploadDeviceConfigToken = 1;</code>
   */
  java.lang.String getUploadDeviceConfigToken();
  /**
   * <code>optional string uploadDeviceConfigToken = 1;</code>
   */
  com.google.protobuf.ByteString
      getUploadDeviceConfigTokenBytes();
}
