// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface UserNotificationDataOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string notificationTitle = 1;
  /**
   * <code>optional string notificationTitle = 1;</code>
   */
  boolean hasNotificationTitle();
  /**
   * <code>optional string notificationTitle = 1;</code>
   */
  java.lang.String getNotificationTitle();
  /**
   * <code>optional string notificationTitle = 1;</code>
   */
  com.google.protobuf.ByteString
      getNotificationTitleBytes();

  // optional string notificationText = 2;
  /**
   * <code>optional string notificationText = 2;</code>
   */
  boolean hasNotificationText();
  /**
   * <code>optional string notificationText = 2;</code>
   */
  java.lang.String getNotificationText();
  /**
   * <code>optional string notificationText = 2;</code>
   */
  com.google.protobuf.ByteString
      getNotificationTextBytes();

  // optional string tickerText = 3;
  /**
   * <code>optional string tickerText = 3;</code>
   */
  boolean hasTickerText();
  /**
   * <code>optional string tickerText = 3;</code>
   */
  java.lang.String getTickerText();
  /**
   * <code>optional string tickerText = 3;</code>
   */
  com.google.protobuf.ByteString
      getTickerTextBytes();

  // optional string dialogTitle = 4;
  /**
   * <code>optional string dialogTitle = 4;</code>
   */
  boolean hasDialogTitle();
  /**
   * <code>optional string dialogTitle = 4;</code>
   */
  java.lang.String getDialogTitle();
  /**
   * <code>optional string dialogTitle = 4;</code>
   */
  com.google.protobuf.ByteString
      getDialogTitleBytes();

  // optional string dialogText = 5;
  /**
   * <code>optional string dialogText = 5;</code>
   */
  boolean hasDialogText();
  /**
   * <code>optional string dialogText = 5;</code>
   */
  java.lang.String getDialogText();
  /**
   * <code>optional string dialogText = 5;</code>
   */
  com.google.protobuf.ByteString
      getDialogTextBytes();
}
