// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface VideoCreditOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 creditType = 1;
  /**
   * <code>optional int32 creditType = 1;</code>
   */
  boolean hasCreditType();
  /**
   * <code>optional int32 creditType = 1;</code>
   */
  int getCreditType();

  // optional string credit = 2;
  /**
   * <code>optional string credit = 2;</code>
   */
  boolean hasCredit();
  /**
   * <code>optional string credit = 2;</code>
   */
  java.lang.String getCredit();
  /**
   * <code>optional string credit = 2;</code>
   */
  com.google.protobuf.ByteString
      getCreditBytes();

  // repeated string name = 3;
  /**
   * <code>repeated string name = 3;</code>
   */
  java.util.List<java.lang.String>
  getNameList();
  /**
   * <code>repeated string name = 3;</code>
   */
  int getNameCount();
  /**
   * <code>repeated string name = 3;</code>
   */
  java.lang.String getName(int index);
  /**
   * <code>repeated string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes(int index);
}
